#! /bin/ksh
# Script to set-up and make the radiation code

here=`pwd`

SRC_LIST="general modules_gen aux scatter correlated_k um"
SRC_LIST=${SRC_LIST}" modules_core radiance_core radiation_control"

echo 'Building the radiation code in bin/'
date

# Create the bin directory and copy across files
mkdir -p bin
cp make/* bin
for SRCDIR in $SRC_LIST
do
  cd src/$SRCDIR
  FILE_LIST=`ls *.f* 2> /dev/null`
  for FILE in $FILE_LIST
  do
    if [ $FILE -nt $here/bin/$FILE ]
      then
        cp $FILE $here/bin/$FILE
    fi
  done
  FILE_LIST=`ls *.F90 2> /dev/null`
  for FILE in $FILE_LIST
  do
    ppfile=$here/bin/${FILE%F90}f90
    if [ $FILE -nt $ppfile ]
      then
        cp $FILE $ppfile
    fi
  done
  cd $here
done

# Build the source code in bin
cd bin
./mkdep
make $1 && echo "All compiled OK"
cd $here

echo "Setting path to distribution in set_rad_env"
sed "s#???#${here}#" sbin/set_rad_env > set_rad_env
grep "LIBCDF_PATH" bin/Mk_cmd | \
sed 's/ *LIBCDF_PATH *= */LIBCDF_PATH=/' >> set_rad_env
echo 'export LD_LIBRARY_PATH=$LIBCDF_PATH:$LD_LIBRARY_PATH' >> set_rad_env

date

exit 0
