#!/bin/bash

# Initialise error status (to test for output differences)
ierr=0

rm -f mcica_data
$RAD_BIN/assign_subcols << EOF > /dev/null
$RAD_DATA/spectra/ga3_0/sp_sw_ga3_0
10
$RAD_DATA/spectra/ga3_0/sp_lw_ga3_0
6
$RAD_DATA/spectra/ga3_0/mcica_data
EOF

diff -q -b mcica_data $RAD_DATA/spectra/ga3_0/mcica_data || ierr=1
if [ $ierr -gt 0 ] ; then
  echo "Output from assign_subcols does not match, test failed"
  exit 1
else
  rm -f mcica_data
fi

cp 5118_142.surflw 5118_142.surf
$RAD_SCRIPT/Cl_run_cdf -B 5118_142 -s $RAD_DATA/spectra/ga3_0/sp_lw_ga3_0 -R 1 9 -I -t 12 +R -v 13 -g 5 -c -C 10 -K 1 -d 1 -i 1 -m 0.75 +m 2 -dp 10000
mv 5118_142.dflx lw_avg.dflx
mv 5118_142.hrts lw_avg.hrts
mv 5118_142.nflx lw_avg.nflx
mv 5118_142.uflx lw_avg.uflx

cp 5118_142.surfsw 5118_142.surf
$RAD_SCRIPT/Cl_run_cdf -B 5118_142 -s $RAD_DATA/spectra/ga3_0/sp_sw_ga3_0 -R 1 6 -S -t 2 +R -v 13 -g 5 -r -C 10 -K 1 -d 3 -i 3 -m 0.75 +m 2 -dp 10000
mv 5118_142.hrts sw_avg.hrts
mv 5118_142.nflx sw_avg.nflx
mv 5118_142.sflx sw_avg.sflx
mv 5118_142.uflx sw_avg.uflx
mv 5118_142.vflx sw_avg.vflx
mv 5118_142.dflx sw_avg.dflx

rm -f cdl_lw*
rm -f cdl_sw*
Ccdf2cdl -a sw_avg > /dev/null
Ccdf2cdl -a lw_avg > /dev/null
diff -q ref_lw_avg.dflx cdl_lw_avg.dflx || ierr=1
diff -q ref_lw_avg.hrts cdl_lw_avg.hrts || ierr=1
diff -q ref_lw_avg.nflx cdl_lw_avg.nflx || ierr=1
diff -q ref_lw_avg.uflx cdl_lw_avg.uflx || ierr=1
diff -q ref_sw_avg.hrts cdl_sw_avg.hrts || ierr=1
diff -q ref_sw_avg.nflx cdl_sw_avg.nflx || ierr=1
diff -q ref_sw_avg.sflx cdl_sw_avg.sflx || ierr=1
diff -q ref_sw_avg.uflx cdl_sw_avg.uflx || ierr=1
diff -q ref_sw_avg.vflx cdl_sw_avg.vflx || ierr=1
diff -q ref_sw_avg.dflx cdl_sw_avg.dflx || ierr=1

if [ $ierr -gt 0 ] ; then
  exit 1
else
  resrm lw_avg
  resrm cdl_lw_avg
  resrm sw_avg
  resrm cdl_sw_avg
  echo OK
  exit 0
fi
