#!/bin/bash

# Initialise error status (to test for output differences)
ierr=0

cp 7460_28.surflw 7460_28.surf
$RAD_SCRIPT/Cl_run_cdf -B 7460_28 -s $RAD_DIR/data/spectra/hadgem1/sp_lw_hadgem1_3 -R 1 9 -I -G 5 0 -t 12 +R -v 11 -g 2 -c -C 2 -K 1 -d 1 -i 1
mv 7460_28.dflx lw_avg.dflx
mv 7460_28.hrts lw_avg.hrts
mv 7460_28.nflx lw_avg.nflx
mv 7460_28.uflx lw_avg.uflx

cp 7460_28.surfsw 7460_28.surf
$RAD_SCRIPT/Cl_run_cdf -B 7460_28 -s $RAD_DIR/data/spectra/hadgem1/sp_sw_hadgem1_3 -R 1 6 -S -G 5 0 -t 2 +R -v 11 -g 2 -r -C 2 -K 1 -d 3 -i 3
mv 7460_28.hrts sw_avg.hrts
mv 7460_28.nflx sw_avg.nflx
mv 7460_28.sflx sw_avg.sflx
mv 7460_28.uflx sw_avg.uflx
mv 7460_28.vflx sw_avg.vflx
mv 7460_28.dflx sw_avg.dflx

cd ipa0

cp 7460_28.surflw 7460_28.surf
$RAD_SCRIPT/Cl_run_cdf -B 7460_28 -s $RAD_DIR/data/spectra/hadgem1/sp_lw_hadgem1_3 -R 1 9 -I -G 5 0 -t 12 +R -v 11 -g 2 -c -C 2 -K 1 -d 1 -i 1
mv 7460_28.dflx lw.dflx
mv 7460_28.hrts lw.hrts
mv 7460_28.nflx lw.nflx
mv 7460_28.uflx lw.uflx

cp 7460_28.surfsw 7460_28.surf
$RAD_SCRIPT/Cl_run_cdf -B 7460_28 -s $RAD_DIR/data/spectra/hadgem1/sp_sw_hadgem1_3 -R 1 6 -S -G 5 0 -t 2 +R -v 11 -g 2 -r -C 2 -K 1 -d 3 -i 3
mv 7460_28.hrts sw.hrts
mv 7460_28.nflx sw.nflx
mv 7460_28.sflx sw.sflx
mv 7460_28.uflx sw.uflx
mv 7460_28.vflx sw.vflx
mv 7460_28.dflx sw.dflx

diff -q ref_lw.dflx lw.dflx || ierr=1
diff -q ref_lw.hrts lw.hrts || ierr=1
diff -q ref_lw.nflx lw.nflx || ierr=1
diff -q ref_lw.uflx lw.uflx || ierr=1
diff -q ref_sw.hrts sw.hrts || ierr=1
diff -q ref_sw.nflx sw.nflx || ierr=1
diff -q ref_sw.sflx sw.sflx || ierr=1
diff -q ref_sw.uflx sw.uflx || ierr=1
diff -q ref_sw.vflx sw.vflx || ierr=1
diff -q ref_sw.dflx sw.dflx || ierr=1
resrm lw
resrm sw

cd ..
rm cdl_sw_avg* 2> /dev/null
Ccdf2cdl -a sw_avg > /dev/null
rm cdl_lw_avg* 2> /dev/null
Ccdf2cdl -a lw_avg > /dev/null
diff -q ref_lw_avg.dflx cdl_lw_avg.dflx || ierr=1
diff -q ref_lw_avg.hrts cdl_lw_avg.hrts || ierr=1
diff -q ref_lw_avg.nflx cdl_lw_avg.nflx || ierr=1
diff -q ref_lw_avg.uflx cdl_lw_avg.uflx || ierr=1
diff -q ref_sw_avg.hrts cdl_sw_avg.hrts || ierr=1
diff -q ref_sw_avg.nflx cdl_sw_avg.nflx || ierr=1
diff -q ref_sw_avg.sflx cdl_sw_avg.sflx || ierr=1
diff -q ref_sw_avg.uflx cdl_sw_avg.uflx || ierr=1
diff -q ref_sw_avg.vflx cdl_sw_avg.vflx || ierr=1
diff -q ref_sw_avg.dflx cdl_sw_avg.dflx || ierr=1
resrm lw_avg
resrm sw_avg

if [ $ierr -gt 0 ] ; then
  exit 1
else
  resrm cdl_lw_avg
  resrm cdl_sw_avg
  echo OK
  exit 0
fi
