#!/bin/bash

sp_dir="/data/users/james.manners/jm_earth_hr"
specfile=${sp_dir}/sp_2000_earth
swref_file=${RAD_DATA}/spectra/ga9_ref/sp_sw_260_jm3
lwref_file=${RAD_DATA}/spectra/ga9_ref/sp_lw_300_jm3
sw9_file="/data/users/james.manners/jm_earth_sw_9/sp_sw_9_earth"

base=tropical

./mk_$base

# SW
cp $base.surfsw $base.surf

Cl_run_cdf -B $base -s ${specfile} -S -R 1 2000 -g 3 -r -c -u -C 5 -sg
fmove $base sw_2000

Cl_run_cdf -B $base -s ${specfile} -S -R 1 2000 -g 3 -r -c -u -C 5 -sg -ch 11232
fmove $base sw_2000_subch

Cl_run_cdf -B $base -s ${swref_file} -S -R 1 260 -g 3 -r -c -C 5 -sg
fmove $base sw_260

Cl_run_cdf -B $base -s ${swref_file} -S -R 1 260 -g 3 -r -c -C 5 -sg -ch 260
fmove $base sw_260_subch

Cl_run_cdf -B $base -s ${sw9_file} -S -R 1 9 -g 4 -r -c -u -C 5 -sg
fmove $base sw_9

Cl_run_cdf -B $base -s ${sw9_file} -S -R 1 9 -g 4 -r -c -u -C 5 -sg -ch 4728
fmove $base sw_9_subch


# LW
cp $base.surflw $base.surf

Cl_run_cdf -B $base -s ${specfile} -I -R 1 2000 -g 2 -c -u -C 5
fmove $base lw_2000

Cl_run_cdf -B $base -s ${specfile} -I -R 1 2000 -g 2 -c -u -C 5 -ch 11232
fmove $base lw_2000_subch

Cl_run_cdf -B $base -s ${lwref_file} -I -R 1 300 -g 2 -c -C 5
fmove $base lw_300

Cl_run_cdf -B $base -s ${lwref_file} -I -R 1 300 -g 2 -c -C 5 -ch 300
fmove $base lw_300_subch
