#!/bin/bash

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

# Set environment variables
procs=24
. ./env_earth

# HITRAN2020 data downloaded from hitran.org on 11.11.22
HITRAN_H2O="${ARCHIVE_DATA}/HITRAN2020/h2o_111122.par"

# MT_CKD 4.3 foreign-broadened continuum
CONT_H2O_FRN="${RAD_DATA}/continua/absco-ref_wv-mt-ckd4p3.nc"

mkdir -p ${SW_DATA}

skelfile="${SW_DATA}/sp_2000_earth_skel"
./mk_sp_2000_earth_skel $skelfile > /dev/null

lbl_base=${H2O_LBL_VIS%.nc}
if [ ! -s ${lbl_base}.nc ] || [ ! -f ${lbl_base}.done ] ; then
  echo "Generating H2O line absorption data: visible"
  rm -f ${lbl_base}*
  ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} -D $HITRAN_H2O \
    -lo 1 -R 505 236 -c 2500.0 -i 0.5 \
    -s $skelfile -m ${lbl_base}_lm -L ${lbl_base}.nc \
    -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -n $procs -o ${lbl_base}_log -t 360 ${ck_args} &
  else
    ${ck_args} > ${lbl_base}_log
  fi
else
  echo "File exists:" $H2O_LBL_VIS
fi

if [ ! -s $H2O_LBL_IRF ] ; then
  ii=0
  echo "Generating H2O line + foreign continuum absorption data: infra-red"
  for ((i = 51; i < 201; i++))
  do
    i_begin=$((i*10-9))
    i_end=$((i*10))
    lbl_base="${SW_DATA}/h2o_blbl_${i_begin}_${i_end}_${PT_FILE}"
    if [ ! -s ${lbl_base}.nc ] || [ ! -f ${lbl_base}.done ] ; then
      rm -f ${lbl_base}*
      ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} -D $HITRAN_H2O \
        -lo 1 -R ${i_end} ${i_begin} -c 2500.0 -i 0.1 -k -x $CONT_H2O_FRN \
        -s $skelfile -m ${lbl_base}_lm -L ${lbl_base}.nc \
        -np $procs"
      if command -v sbatch &> /dev/null ; then
        sbatch -W -n $procs -o ${lbl_base}_log -t 120 ${ck_args} &
      else
        ${ck_args} > ${lbl_base}_log
      fi
      ((ii++))
    fi
    if [ $ii -gt 99 ] ; then
      wait -n
    fi
  done

  wait
  finished="true"

  echo "Checking all bands have been completed"
  for ((i = 51; i < 201; i++))
  do
    i_begin=$((i*10-9))
    i_end=$((i*10))
    lbl_base="${SW_DATA}/h2o_blbl_${i_begin}_${i_end}_${PT_FILE}"
    if [ ! -f ${lbl_base}.done ] ; then
      echo "Bands" ${i_begin} "-" ${i_end} "not done"
      finished="false" 
    fi
  done
  if [ $finished == "true" ] ; then
    echo "Concatenating band data into a single file"
    lblcat ${SW_DATA}/h2o_blbl_*_${PT_FILE}.nc $H2O_LBL_IRF
  else
    echo "Not concatenating band data: check for errors and rerun"
    exit 1
  fi
else
  echo "File exists:" $H2O_LBL_IRF
fi

# Check job progress using:
# sacct --format=jobname%30,jobid%9,elapsed,totalcpu,ncpus%5,reqmem,exitcode,state
# Use scancel to kill

exit 0
