#!/bin/bash

echo -n 'Started mk_sp_2000_earth: '; date

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

# Set environment variables
# -------------------------
procs=4
procs_s=8
. ./env_earth

sp_dir="/data/users/james.manners/jm_earth_hr"
mkdir -p ${sp_dir}


# Create skeleton spectral file
# -----------------------------
specfile=${sp_dir}/sp_2000_earth
skelfile=${sp_dir}/sp_2000_earth_skel
rm -f $skelfile
./mk_sp_2000_earth_skel $skelfile > /dev/null


# Gas absorption coefficients:
# ----------------------------
# Water vapour (H2O)
# ----------------------------
uv_h2o=${sp_dir}/h2o.uvxsc
rm -f $uv_h2o
dat2xsc h2o_298K_Hebrard2022.dat $uv_h2o  #  6 - 216 nm
if [ ! -s ${sp_dir}/h2o_xuv_l ] ; then
  echo 'H2O: XUV - cross-section'
  rm -f ${sp_dir}/h2o_xuv_l* ${sp_dir}/h2o_lbl_xuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_h2o \
    -R 6 10 -i 1000.0 -l $IP_H2O 1.0e-5 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/h2o_xuv_l -m ${sp_dir}/h2o_xuv_lm \
    -L ${sp_dir}/h2o_lbl_xuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/h2o_xuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/h2o_xuv_log
  fi
fi
if [ ! -s ${sp_dir}/h2o_euv_l ] ; then
  echo 'H2O: extreme UV - cross-section'
  rm -f ${sp_dir}/h2o_euv_l* ${sp_dir}/h2o_lbl_euv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_h2o \
    -R 11 100 -i 10.0 -l $IP_H2O 1.0e-5 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/h2o_euv_l -m ${sp_dir}/h2o_euv_lm \
    -L ${sp_dir}/h2o_lbl_euv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/h2o_euv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/h2o_euv_log
  fi
fi
if [ ! -s ${sp_dir}/h2o_fuv_l ] ; then
  echo 'H2O: far UV - cross-section'
  rm -f ${sp_dir}/h2o_fuv_l* ${sp_dir}/h2o_lbl_fuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_h2o \
    -R 101 217 -i 1.0 -l $IP_H2O 1.0e-5 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/h2o_fuv_l -m ${sp_dir}/h2o_fuv_lm \
    -L ${sp_dir}/h2o_lbl_fuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/h2o_fuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/h2o_fuv_log
  fi
fi

if [ ! -s $sp_dir/h2o_nuv_l ] ; then
  if [ ! -s $H2O_LBL_VIS ] ; then
    echo "H2O: No visible LBL file: please run ./mk_h2o_lbl_2000_earth"
    exit 1
  else
    echo "H2O: near UV - lines"
    rm -f $sp_dir/h2o_nuv_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 238 320 -l $IP_H2O ${COL_MASS_K_H2O} -b 5.0e-4 \
      -s $skelfile +S $SOLSPEC -lk \
      -o $sp_dir/h2o_nuv_l -m $sp_dir/h2o_nuv_lm \
      -L $H2O_LBL_VIS -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/h2o_nuv_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/h2o_nuv_log
    fi
  fi
fi
if [ ! -s $sp_dir/h2o_vis_l ] ; then
  if [ ! -s $H2O_LBL_VIS ] ; then
    echo "H2O: No visible LBL file: please run ./mk_h2o_lbl_2000_earth"
    exit 1
  else
    echo "H2O: visible"
    rm -f $sp_dir/h2o_vis_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 321 500 -l $IP_H2O ${COL_MASS_K_H2O} -b 5.0e-4 \
      -s $skelfile +S $SOLSPEC -lk \
      -o $sp_dir/h2o_vis_l -m $sp_dir/h2o_vis_lm \
      -L $H2O_LBL_VIS -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/h2o_vis_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/h2o_vis_log &
    fi
  fi
fi
if [ ! -s $sp_dir/h2o_nirf_l ] ; then
  if [ ! -s $H2O_LBL_IRF ] ; then
    echo "H2O: No infra-red LBL file: please run ./mk_h2o_lbl_2000_earth"
    exit 1
  else
    echo "H2O: near infra-red"
    rm -f $sp_dir/h2o_nirf_l*
    rm -f $sp_dir/h2o_nirf_l_map.nc
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 501 1000 -l $IP_H2O ${COL_MASS_K_H2O} -b 5.0e-4 \
      -s $skelfile +S $SOLSPEC -lk \
      -o $sp_dir/h2o_nirf_l -m $sp_dir/h2o_nirf_lm \
      -L $H2O_LBL_IRF -np $procs \
      -sm $sp_dir/h2o_nirf_l_map.nc"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/h2o_nirf_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/h2o_nirf_log
    fi
  fi
fi
if [ ! -s $sp_dir/h2o_mirf_l ] ; then
  if [ ! -s $H2O_LBL_IRF ] ; then
    echo "H2O: No infra-red LBL file: please run ./mk_h2o_lbl_2000_earth"
    exit 1
  else
    echo "H2O: mid infra-red"
    rm -f $sp_dir/h2o_mirf_l*
    rm -f $sp_dir/h2o_mirf_l_map.nc
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1001 1500 -l $IP_H2O ${COL_MASS_K_H2O} -b 5.0e-4 \
      -s $skelfile -u -lk \
      -o $sp_dir/h2o_mirf_l -m $sp_dir/h2o_mirf_lm \
      -L $H2O_LBL_IRF -np $procs \
      -sm $sp_dir/h2o_mirf_l_map.nc"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/h2o_mirf_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/h2o_mirf_log
    fi
  fi
fi
if [ ! -s $sp_dir/h2o_firf_l ] ; then
  if [ ! -s $H2O_LBL_IRF ] ; then
    echo "H2O: No infra-red LBL file: please run ./mk_h2o_lbl_2000_earth"
    exit 1
  else
    echo "H2O: far infra-red"
    rm -f $sp_dir/h2o_firf_l*
    rm -f $sp_dir/h2o_firf_l_map.nc
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1501 2000 -l $IP_H2O ${COL_MASS_K_H2O} -b 5.0e-4 \
      -s $skelfile -u -lk \
      -o $sp_dir/h2o_firf_l -m $sp_dir/h2o_firf_lm \
      -L $H2O_LBL_IRF -np $procs \
      -sm $sp_dir/h2o_firf_l_map.nc"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/h2o_firf_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/h2o_firf_log
    fi
  fi
fi
if [ ! -s $sp_dir/h2o_nir_s ] ; then
  if [ ! -s $H2O_LBL_IRF ] ; then
    echo "H2O: No infra-red LBL file: please run ./mk_h2o_lbl_2000_earth"
    exit 1
  else
    echo "H2O: near-ir self-broadened continuum"
    rm -f $sp_dir/h2o_nir_s*
	  ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 501 1000 -C 33 1.0e-4 1.0e4 -P 7 \
      -e ${CONT_H2O_S260} ${CONT_H2O_S260} \
      -s $skelfile -u -p -r ${REF_PT_FILE} \
      -o $sp_dir/h2o_nir_s -m $sp_dir/h2o_nir_sm \
      -L $H2O_LBL_IRF -np $procs_s"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs_s -o $sp_dir/h2o_nir_s_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/h2o_nir_s_log
    fi
  fi
fi
if [ ! -s $sp_dir/h2o_mir_s ] ; then
  if [ ! -s $H2O_LBL_IRF ] ; then
    echo "H2O: No infra-red LBL file: please run ./mk_h2o_lbl_2000_earth"
    exit 1
  else
    echo "H2O: mid-ir self-broadened continuum"
    rm -f $sp_dir/h2o_mir_s*
	  ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1001 1500 -C 33 1.0e-4 1.0e4 -P 7 \
      -e ${CONT_H2O_S260} ${CONT_H2O_S260} \
      -s $skelfile -u -p -r ${REF_PT_FILE} \
      -o $sp_dir/h2o_mir_s -m $sp_dir/h2o_mir_sm \
      -L $H2O_LBL_IRF -np $procs_s"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs_s -o $sp_dir/h2o_mir_s_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/h2o_mir_s_log
    fi
  fi
fi
if [ ! -s $sp_dir/h2o_fir_s ] ; then
  if [ ! -s $H2O_LBL_IRF ] ; then
    echo "H2O: No infra-red LBL file: please run ./mk_h2o_lbl_2000_earth"
    exit 1
  else
    echo "H2O: far-ir self-broadened continuum"
    rm -f $sp_dir/h2o_fir_s*
	  ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1501 2000 -C 33 1.0e-4 1.0e4 -P 7 \
      -e ${CONT_H2O_S260} ${CONT_H2O_S260} \
      -s $skelfile -u -p -r ${REF_PT_FILE} \
      -o $sp_dir/h2o_fir_s -m $sp_dir/h2o_fir_sm \
      -L $H2O_LBL_IRF -np $procs_s"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs_s -o $sp_dir/h2o_fir_s_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/h2o_fir_s_log
    fi
  fi
fi


# ----------------------------
# Carbon Dioxide (CO2)
# ----------------------------
uv_co2=${sp_dir}/co2.uvxsc
rm -f $uv_co2
dat2xsc co2_300K_HuestisBerkowitz2010.dat $uv_co2  #  0.1254-201.6nm
if [ ! -s ${sp_dir}/co2_xuv_l ] ; then
  echo 'CO2: XUV - cross-section'
  rm -f ${sp_dir}/co2_xuv_l* ${sp_dir}/co2_lbl_xuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_co2 \
    -R 1 10 -i 1000.0 -l $IP_CO2 ${COL_MASS_K_CO2} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/co2_xuv_l -m ${sp_dir}/co2_xuv_lm \
    -L ${sp_dir}/co2_lbl_xuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/co2_xuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/co2_xuv_log
  fi
fi
if [ ! -s ${sp_dir}/co2_euv_l ] ; then
  echo 'CO2: extreme UV - cross-section'
  rm -f ${sp_dir}/co2_euv_l* ${sp_dir}/co2_lbl_euv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_co2 \
    -R 11 100 -i 10.0 -l $IP_CO2 ${COL_MASS_K_CO2} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/co2_euv_l -m ${sp_dir}/co2_euv_lm \
    -L ${sp_dir}/co2_lbl_euv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/co2_euv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/co2_euv_log
  fi
fi
if [ ! -s ${sp_dir}/co2_fuv_l ] ; then
  echo 'CO2: far UV - cross-section'
  rm -f ${sp_dir}/co2_fuv_l* ${sp_dir}/co2_lbl_fuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_co2 \
    -R 101 202 -i 1.0 -l $IP_CO2 ${COL_MASS_K_CO2} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/co2_fuv_l -m ${sp_dir}/co2_fuv_lm \
    -L ${sp_dir}/co2_lbl_fuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/co2_fuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/co2_fuv_log
  fi
fi

if [ ! -s $sp_dir/co2_nir_l ] ; then
  if [ ! -s $CO2_LBL ] ; then
    echo "CO2: No LBL file: please run ./mk_co2_lbl_2000_earth"
    exit 1
  else
    echo "CO2: near infra-red"
    rm -f $sp_dir/co2_nir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 547 1000 -l $IP_CO2 ${COL_MASS_K_CO2} -b 5.0e-4 \
      -s $skelfile +S $SOLSPEC -lk \
      -o $sp_dir/co2_nir_l -m $sp_dir/co2_nir_lm \
      -L $CO2_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/co2_nir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/co2_nir_log
    fi
  fi
fi
if [ ! -s $sp_dir/co2_mir_l ] ; then
  if [ ! -s $CO2_LBL ] ; then
    echo "CO2: No LBL file: please run ./mk_co2_lbl_2000_earth"
    exit 1
  else
    echo "CO2: mid infra-red"
    rm -f $sp_dir/co2_mir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1001 1500 -l $IP_CO2 ${COL_MASS_K_CO2} -b 5.0e-4 \
      -s $skelfile -u -lk \
      -o $sp_dir/co2_mir_l -m $sp_dir/co2_mir_lm \
      -L $CO2_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/co2_mir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/co2_mir_log
    fi
  fi
fi
if [ ! -s $sp_dir/co2_fir_l ] ; then
  if [ ! -s $CO2_LBL ] ; then
    echo "CO2: No LBL file: please run ./mk_co2_lbl_2000_earth"
    exit 1
  else
    echo "CO2: far infra-red"
    rm -f $sp_dir/co2_fir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1501 2000 -l $IP_CO2 ${COL_MASS_K_CO2} -b 5.0e-4 \
      -s $skelfile -u -lk \
      -o $sp_dir/co2_fir_l -m $sp_dir/co2_fir_lm \
      -L $CO2_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/co2_fir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/co2_fir_log
    fi
  fi
fi

# ----------------------------
# Ozone (O3)
# ----------------------------
uv_o3="$RAD_DATA/gases/O3_110nm-1100nm.xsc"
o3_pt_file="$RAD_DATA/gases/pt_o3_uv"
if [ ! -s ${sp_dir}/o3_uv_l ] ; then
  echo 'O3: far-UV - near-IR cross-section'
  rm -f ${sp_dir}/o3_uv_l* ${sp_dir}/o3_lbl_uv*
  ck_args="Ccorr_k -F $o3_pt_file -X $uv_o3 \
    -R 111 1091 -i 1.0 -l $IP_O3 ${COL_MASS_K_O3} -t 1.0e-3 \
    -s $skelfile +S $SOLSPEC -lk \
    -o ${sp_dir}/o3_uv_l -m ${sp_dir}/o3_uv_lm \
    -L ${sp_dir}/o3_lbl_uv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/o3_uv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/o3_uv_log
  fi
fi
if [ ! -s $sp_dir/o3_mir_l ] ; then
  if [ ! -s $O3_LBL ] ; then
    echo "O3: No LBL file: please run ./mk_o3_lbl_2000_earth"
    exit 1
  else
    echo "O3: mid infra-red"
    rm -f $sp_dir/o3_mir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1251 1500 -l $IP_O3 ${COL_MASS_K_O3} -b 5.0e-4 \
      -s $skelfile -u -lk \
      -o $sp_dir/o3_mir_l -m $sp_dir/o3_mir_lm \
      -L $O3_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/o3_mir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/o3_mir_log
    fi
  fi
fi
if [ ! -s $sp_dir/o3_fir_l ] ; then
  if [ ! -s $O3_LBL ] ; then
    echo "O3: No LBL file: please run ./mk_o3_lbl_2000_earth"
    exit 1
  else
    echo "O3: far infra-red"
    rm -f $sp_dir/o3_fir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1501 2000 -l $IP_O3 ${COL_MASS_K_O3} -b 5.0e-4 \
      -s $skelfile -u -lk \
      -o $sp_dir/o3_fir_l -m $sp_dir/o3_fir_lm \
      -L $O3_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/o3_fir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/o3_fir_log
    fi
  fi
fi

# ----------------------------
# Dinitrogen Oxide (N2O)
# ----------------------------
uv_n2o=${sp_dir}/n2o_208-298K.uvxsc  #  6 - 250 nm
n2o_pt_file="pt_n2o"

if [ ! -s $uv_n2o ] ; then
  rm -f n2o_???K.dat n2o_???K.uvxsc n2o_298K_ext.uvxsc
  calc_n2o_xsc
  cat n2o_298K_6-160nm.dat n2o_298K.dat > n2o_298K_ext.dat
  dat2xsc -t 208 n2o_208K.dat n2o_208K.uvxsc
  dat2xsc -t 238 n2o_238K.dat n2o_238K.uvxsc
  dat2xsc -t 268 n2o_268K.dat n2o_268K.uvxsc
  dat2xsc -t 298 n2o_298K_ext.dat n2o_298K_ext.uvxsc
  cat n2o_208K.uvxsc n2o_238K.uvxsc n2o_268K.uvxsc n2o_298K_ext.uvxsc > $uv_n2o
  rm -f n2o_???K.dat n2o_???K.uvxsc n2o_298K_ext.uvxsc n2o_298K_ext.dat
fi

if [ ! -s ${sp_dir}/n2o_xuv_l ] ; then
  echo 'N2O: XUV cross-section'
  rm -f ${sp_dir}/n2o_xuv_l* ${sp_dir}/n2o_lbl_xuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_n2o \
    -R 7 10 -i 1000.0 -l $IP_N2O ${COL_MASS_K_N2O} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/n2o_xuv_l -m ${sp_dir}/n2o_xuv_lm \
    -L ${sp_dir}/n2o_lbl_xuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/n2o_xuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/n2o_xuv_log
  fi
fi
if [ ! -s ${sp_dir}/n2o_euv_l ] ; then
  echo 'N2O: EUV cross-section'
  rm -f ${sp_dir}/n2o_euv_l* ${sp_dir}/n2o_lbl_euv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_n2o \
    -R 11 100 -i 10.0 -l $IP_N2O ${COL_MASS_K_N2O} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/n2o_euv_l -m ${sp_dir}/n2o_euv_lm \
    -L ${sp_dir}/n2o_lbl_euv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/n2o_euv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/n2o_euv_log
  fi
fi
if [ ! -s ${sp_dir}/n2o_fuv_l ] ; then
  echo 'N2O: FUV cross-section'
  rm -f ${sp_dir}/n2o_fuv_l* ${sp_dir}/n2o_lbl_fuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_n2o \
    -R 101 160 -i 1.0 -l $IP_N2O ${COL_MASS_K_N2O} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/n2o_fuv_l -m ${sp_dir}/n2o_fuv_lm \
    -L ${sp_dir}/n2o_lbl_fuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/n2o_fuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/n2o_fuv_log
  fi
fi
if [ ! -s ${sp_dir}/n2o_uv_l ] ; then
  echo 'N2O: UV cross-section'
  rm -f ${sp_dir}/n2o_uv_l* ${sp_dir}/n2o_lbl_uv*
  ck_args="Ccorr_k -F $n2o_pt_file -UVX $uv_n2o \
    -R 161 250 -i 1.0 -l $IP_N2O ${COL_MASS_K_N2O} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -lk \
    -o ${sp_dir}/n2o_uv_l -m ${sp_dir}/n2o_uv_lm \
    -L ${sp_dir}/n2o_lbl_uv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/n2o_uv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/n2o_uv_log
  fi
fi

if [ ! -s $sp_dir/n2o_nir_l ] ; then
  if [ ! -s $N2O_LBL ] ; then
    echo "N2O: No LBL file: please run ./mk_n2o_lbl_2000_earth"
    exit 1
  else
    echo "N2O: near infra-red"
    rm -f $sp_dir/n2o_nir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 686 1000 -l $IP_N2O ${COL_MASS_K_N2O} -b 5.0e-4 \
      -s $skelfile +S $SOLSPEC -lk \
      -o $sp_dir/n2o_nir_l -m $sp_dir/n2o_nir_lm \
      -L $N2O_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/n2o_nir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/n2o_nir_log
    fi
  fi
fi
if [ ! -s $sp_dir/n2o_mir_l ] ; then
  if [ ! -s $N2O_LBL ] ; then
    echo "N2O: No LBL file: please run ./mk_n2o_lbl_2000_earth"
    exit 1
  else
    echo "N2O: mid infra-red"
    rm -f $sp_dir/n2o_mir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1001 1500 -l $IP_N2O ${COL_MASS_K_N2O} -b 5.0e-4 \
      -s $skelfile -u -lk \
      -o $sp_dir/n2o_mir_l -m $sp_dir/n2o_mir_lm \
      -L $N2O_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/n2o_mir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/n2o_mir_log
    fi
  fi
fi
if [ ! -s $sp_dir/n2o_fir_l ] ; then
  if [ ! -s $N2O_LBL ] ; then
    echo "N2O: No LBL file: please run ./mk_n2o_lbl_2000_earth"
    exit 1
  else
    echo "N2O: far infra-red"
    rm -f $sp_dir/n2o_fir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1501 2000 -l $IP_N2O ${COL_MASS_K_N2O} -b 5.0e-4 \
      -s $skelfile -u -lk \
      -o $sp_dir/n2o_fir_l -m $sp_dir/n2o_fir_lm \
      -L $N2O_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/n2o_fir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/n2o_fir_log
    fi
  fi
fi

# ----------------------------
# Carbon Monoxide (CO)
# ----------------------------
uv_co=${sp_dir}/co.uvxsc
rm -f $uv_co
dat2xsc --offset co_Venot2012.dat $uv_co  #  7.5 - 163.5 nm
if [ ! -s ${sp_dir}/co_xuv_l ] ; then
  echo 'CO: XUV cross-section'
  rm -f ${sp_dir}/co_xuv_l* ${sp_dir}/co_lbl_xuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_co \
    -R 8 10 -i 1000.0 -l $IP_CO ${COL_MASS_K_CO} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/co_xuv_l -m ${sp_dir}/co_xuv_lm \
    -L ${sp_dir}/co_lbl_xuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/co_xuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/co_xuv_log
  fi
fi
if [ ! -s ${sp_dir}/co_euv_l ] ; then
  echo 'CO: EUV cross-section'
  rm -f ${sp_dir}/co_euv_l* ${sp_dir}/co_lbl_euv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_co \
    -R 11 100 -i 10.0 -l $IP_CO ${COL_MASS_K_CO} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/co_euv_l -m ${sp_dir}/co_euv_lm \
    -L ${sp_dir}/co_lbl_euv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/co_euv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/co_euv_log
  fi
fi
if [ ! -s ${sp_dir}/co_fuv_l ] ; then
  echo 'CO: FUV cross-section'
  rm -f ${sp_dir}/co_fuv_l* ${sp_dir}/co_lbl_fuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_co \
    -R 101 164 -i 1.0 -l $IP_CO ${COL_MASS_K_CO} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/co_fuv_l -m ${sp_dir}/co_fuv_lm \
    -L ${sp_dir}/co_lbl_fuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/co_fuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/co_fuv_log
  fi
fi

if [ ! -s $sp_dir/co_nir_l ] ; then
  if [ ! -s $CO_LBL ] ; then
    echo "CO: No LBL file: please run ./mk_co_lbl_2000_earth"
    exit 1
  else
    echo "CO: near infra-red"
    rm -f $sp_dir/co_nir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 666 1000 -l $IP_CO ${COL_MASS_K_CO} -b 5.0e-4 \
      -s $skelfile +S $SOLSPEC -lk \
      -o $sp_dir/co_nir_l -m $sp_dir/co_nir_lm \
      -L $CO_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/co_nir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/co_nir_log
    fi
  fi
fi
if [ ! -s $sp_dir/co_mir_l ] ; then
  if [ ! -s $CO_LBL ] ; then
    echo "CO: No LBL file: please run ./mk_co_lbl_2000_earth"
    exit 1
  else
    echo "CO: mid infra-red"
    rm -f $sp_dir/co_mir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1001 1500 -l $IP_CO ${COL_MASS_K_CO} -b 5.0e-4 \
      -s $skelfile -u -lk \
      -o $sp_dir/co_mir_l -m $sp_dir/co_mir_lm \
      -L $CO_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/co_mir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/co_mir_log
    fi
  fi
fi
if [ ! -s $sp_dir/co_fir_l ] ; then
  if [ ! -s $CO_LBL ] ; then
    echo "CO: No LBL file: please run ./mk_co_lbl_2000_earth"
    exit 1
  else
    echo "CO: far infra-red"
    rm -f $sp_dir/co_fir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1501 2000 -l $IP_CO ${COL_MASS_K_CO} -b 5.0e-4 \
      -s $skelfile -u -lk \
      -o $sp_dir/co_fir_l -m $sp_dir/co_fir_lm \
      -L $CO_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/co_fir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/co_fir_log
    fi
  fi
fi

# ----------------------------
# Methane (CH4)
# ----------------------------
uv_ch4=${sp_dir}/ch4.uvxsc
rm -f $uv_ch4
dat2xsc --offset ch4_Venot2012.dat $uv_ch4  #  6.5 - 151.5 nm
if [ ! -s ${sp_dir}/ch4_xuv_l ] ; then
  echo 'CH4: XUV cross-section'
  rm -f ${sp_dir}/ch4_xuv_l* ${sp_dir}/ch4_lbl_xuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_ch4 \
    -R 7 10 -i 1000.0 -l $IP_CH4 ${COL_MASS_K_CH4} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/ch4_xuv_l -m ${sp_dir}/ch4_xuv_lm \
    -L ${sp_dir}/ch4_lbl_xuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/ch4_xuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/ch4_xuv_log
  fi
fi
if [ ! -s ${sp_dir}/ch4_euv_l ] ; then
  echo 'CH4: EUV cross-section'
  rm -f ${sp_dir}/ch4_euv_l* ${sp_dir}/ch4_lbl_euv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_ch4 \
    -R 11 100 -i 10.0 -l $IP_CH4 ${COL_MASS_K_CH4} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/ch4_euv_l -m ${sp_dir}/ch4_euv_lm \
    -L ${sp_dir}/ch4_lbl_euv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/ch4_euv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/ch4_euv_log
  fi
fi
if [ ! -s ${sp_dir}/ch4_fuv_l ] ; then
  echo 'CH4: FUV cross-section'
  rm -f ${sp_dir}/ch4_fuv_l* ${sp_dir}/ch4_lbl_fuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_ch4 \
    -R 101 152 -i 1.0 -l $IP_CH4 ${COL_MASS_K_CH4} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/ch4_fuv_l -m ${sp_dir}/ch4_fuv_lm \
    -L ${sp_dir}/ch4_lbl_fuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/ch4_fuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/ch4_fuv_log
  fi
fi

if [ ! -s $sp_dir/ch4_nir_l ] ; then
  if [ ! -s $CH4_LBL ] ; then
    echo "CH4: No LBL file: please run ./mk_ch4_lbl_2000_earth"
    exit 1
  else
    echo "CH4: near infra-red"
    rm -f $sp_dir/ch4_nir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 691 1000 -l $IP_CH4 ${COL_MASS_K_CH4} -b 5.0e-4 \
      -s $skelfile +S $SOLSPEC -lk \
      -o $sp_dir/ch4_nir_l -m $sp_dir/ch4_nir_lm \
      -L $CH4_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/ch4_nir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/ch4_nir_log
    fi
  fi
fi
if [ ! -s $sp_dir/ch4_mir_l ] ; then
  if [ ! -s $CH4_LBL ] ; then
    echo "CH4: No LBL file: please run ./mk_ch4_lbl_2000_earth"
    exit 1
  else
    echo "CH4: mid infra-red"
    rm -f $sp_dir/ch4_mir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1001 1500 -l $IP_CH4 ${COL_MASS_K_CH4} -b 5.0e-4 \
      -s $skelfile -u -lk \
      -o $sp_dir/ch4_mir_l -m $sp_dir/ch4_mir_lm \
      -L $CH4_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/ch4_mir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/ch4_mir_log
    fi
  fi
fi
if [ ! -s $sp_dir/ch4_fir_l ] ; then
  if [ ! -s $CH4_LBL ] ; then
    echo "CH4: No LBL file: please run ./mk_ch4_lbl_2000_earth"
    exit 1
  else
    echo "CH4: far infra-red"
    rm -f $sp_dir/ch4_fir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1501 2000 -l $IP_CH4 ${COL_MASS_K_CH4} -b 5.0e-4 \
      -s $skelfile -u -lk \
      -o $sp_dir/ch4_fir_l -m $sp_dir/ch4_fir_lm \
      -L $CH4_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/ch4_fir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/ch4_fir_log
    fi
  fi
fi

# ----------------------------
# Oxygen (O2)
# ----------------------------
uv_o2=${sp_dir}/o2.uvxsc
rm -f $uv_o2
dat2xsc o2_Manners2024.dat $uv_o2  #  0.04 - 294 nm
if [ ! -s ${sp_dir}/o2_xuv_l ] ; then
  echo 'O2: XUV cross-section'
  rm -f ${sp_dir}/o2_xuv_l* ${sp_dir}/o2_lbl_xuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_o2 \
    -R 1 10 -i 1000.0 -l $IP_O2 ${COL_MASS_K_O2} -t 5.0e-4  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/o2_xuv_l -m ${sp_dir}/o2_xuv_lm \
    -L ${sp_dir}/o2_lbl_xuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/o2_xuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/o2_xuv_log
  fi
fi
if [ ! -s ${sp_dir}/o2_euv_l ] ; then
  echo 'O2: EUV cross-section'
  rm -f ${sp_dir}/o2_euv_l* ${sp_dir}/o2_lbl_euv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_o2 \
    -R 11 100 -i 10.0 -l $IP_O2 ${COL_MASS_K_O2} -t 5.0e-4  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/o2_euv_l -m ${sp_dir}/o2_euv_lm \
    -L ${sp_dir}/o2_lbl_euv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/o2_euv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/o2_euv_log
  fi
fi
if [ ! -s ${sp_dir}/o2_fuv_l ] ; then
  echo 'O2: FUV cross-section'
  rm -f ${sp_dir}/o2_fuv_l* ${sp_dir}/o2_lbl_fuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_o2 \
    -R 101 181 -i 1.0 -l $IP_O2 ${COL_MASS_K_O2} -t 5.0e-4  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/o2_fuv_l -m ${sp_dir}/o2_fuv_lm \
    -L ${sp_dir}/o2_lbl_fuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/o2_fuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/o2_fuv_log
  fi
fi
if [ ! -s ${sp_dir}/o2_duv_l ] ; then
  echo 'O2: UV - cross-section between NO delta bands'
  rm -f ${sp_dir}/o2_duv_l* ${sp_dir}/o2_lbl_duv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_o2 \
    -R 185 189 -i 1.0 -l $IP_O2 ${COL_MASS_K_O2} -t 5.0e-4  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/o2_duv_l -m ${sp_dir}/o2_duv_lm \
    -L ${sp_dir}/o2_lbl_duv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/o2_duv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/o2_duv_log
  fi
fi
if [ ! -s ${sp_dir}/o2_uv_l ] ; then
  echo 'O2: UV - cross-section'
  rm -f ${sp_dir}/o2_uv_l* ${sp_dir}/o2_lbl_uv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_o2 \
    -R 193 295 -i 1.0 -l $IP_O2 ${COL_MASS_K_O2} -t 5.0e-4  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/o2_uv_l -m ${sp_dir}/o2_uv_lm \
    -L ${sp_dir}/o2_lbl_uv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/o2_uv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/o2_uv_log
  fi
fi

if [ ! -s $sp_dir/o2_d1l_l ] ; then
  if [ ! -s $O2_LBL ] ; then
    echo "O2: No LBL file: please run ./mk_o2_lbl_2000_earth"
    exit 1
  else
    echo "O2: UV NO d(1-0) - lines"
    rm -f $sp_dir/o2_d1l_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 182 184 -l $IP_O2 ${COL_MASS_K_O2} -b 5.0e-4 \
      -s $skelfile +S $SOLSPEC -lk \
      -o $sp_dir/o2_d1l_l -m $sp_dir/o2_d1l_lm \
      -L $O2_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/o2_d1l_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/o2_d1l_log
    fi
  fi
fi
if [ ! -s $sp_dir/o2_d0l_l ] ; then
  if [ ! -s $O2_LBL ] ; then
    echo "O2: No LBL file: please run ./mk_o2_lbl_2000_earth"
    exit 1
  else
    echo "O2: UV NO d(0-0) - lines"
    rm -f $sp_dir/o2_d0l_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 190 192 -l $IP_O2 ${COL_MASS_K_O2} -b 5.0e-4 \
      -s $skelfile +S $SOLSPEC -lk \
      -o $sp_dir/o2_d0l_l -m $sp_dir/o2_d0l_lm \
      -L $O2_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/o2_d0l_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/o2_d0l_log
    fi
  fi
fi

if [ ! -s $sp_dir/o2_nir_l ] ; then
  if [ ! -s $O2_LBL ] ; then
    echo "O2: No LBL file: please run ./mk_o2_lbl_2000_earth"
    exit 1
  else
    echo "O2: near infra-red"
    rm -f $sp_dir/o2_nir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 560 919 -l $IP_O2 ${COL_MASS_K_O2} -b 5.0e-4 \
      -s $skelfile +S $SOLSPEC -lk \
      -o $sp_dir/o2_nir_l -m $sp_dir/o2_nir_lm \
      -L $O2_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/o2_nir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/o2_nir_log
    fi
  fi
fi
if [ ! -s $sp_dir/o2_mir_l ] ; then
  if [ ! -s $O2_LBL ] ; then
    echo "O2: No LBL file: please run ./mk_o2_lbl_2000_earth"
    exit 1
  else
    echo "O2: mid infra-red"
    rm -f $sp_dir/o2_mir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 988 1500 -l $IP_O2 ${COL_MASS_K_O2} -b 5.0e-4 \
      -s $skelfile -u -lk \
      -o $sp_dir/o2_mir_l -m $sp_dir/o2_mir_lm \
      -L $O2_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/o2_mir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/o2_mir_log
    fi
  fi
fi
if [ ! -s $sp_dir/o2_fir_l ] ; then
  if [ ! -s $O2_LBL ] ; then
    echo "O2: No LBL file: please run ./mk_o2_lbl_2000_earth"
    exit 1
  else
    echo "O2: far infra-red"
    rm -f $sp_dir/o2_fir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1501 2000 -l $IP_O2 ${COL_MASS_K_O2} -b 5.0e-4 \
      -s $skelfile -u -lk \
      -o $sp_dir/o2_fir_l -m $sp_dir/o2_fir_lm \
      -L $O2_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/o2_fir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/o2_fir_log
    fi
  fi
fi

# ----------------------------
# Nitric Oxide (NO)
# ----------------------------
uv_no=${sp_dir}/no.uvxsc
rm -f $uv_no
dat2xsc no_298K_Iida86_Chang93.dat $uv_no  #  6.5 - 228.5 nm
if [ ! -s ${sp_dir}/no_xuv_l ] ; then
  echo 'NO: XUV cross-section'
  rm -f ${sp_dir}/no_xuv_l* ${sp_dir}/no_lbl_xuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_no \
    -R 7 10 -i 1000.0 -l $IP_NO ${COL_MASS_K_NO} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/no_xuv_l -m ${sp_dir}/no_xuv_lm \
    -L ${sp_dir}/no_lbl_xuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/no_xuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/no_xuv_log
  fi
fi
if [ ! -s ${sp_dir}/no_euv_l ] ; then
  echo 'NO: EUV cross-section'
  rm -f ${sp_dir}/no_euv_l* ${sp_dir}/no_lbl_euv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_no \
    -R 11 100 -i 10.0 -l $IP_NO ${COL_MASS_K_NO} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/no_euv_l -m ${sp_dir}/no_euv_lm \
    -L ${sp_dir}/no_lbl_euv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/no_euv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/no_euv_log
  fi
fi
if [ ! -s ${sp_dir}/no_fuv_l ] ; then
  echo 'NO: FUV cross-section'
  rm -f ${sp_dir}/no_fuv_l* ${sp_dir}/no_lbl_fuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_no \
    -R 101 181 -i 1.0 -l $IP_NO ${COL_MASS_K_NO} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/no_fuv_l -m ${sp_dir}/no_fuv_lm \
    -L ${sp_dir}/no_lbl_fuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/no_fuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/no_fuv_log
  fi
fi
if [ ! -s ${sp_dir}/no_duv_l ] ; then
  echo 'NO: UV cross-section between delta bands'
  rm -f ${sp_dir}/no_duv_l* ${sp_dir}/no_lbl_duv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_no \
    -R 185 189 -i 1.0 -l $IP_NO ${COL_MASS_K_NO} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/no_duv_l -m ${sp_dir}/no_duv_lm \
    -L ${sp_dir}/no_lbl_duv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/no_duv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/no_duv_log
  fi
fi
if [ ! -s ${sp_dir}/no_uv_l ] ; then
  echo 'NO: UV cross-section'
  rm -f ${sp_dir}/no_uv_l* ${sp_dir}/no_lbl_uv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_no \
    -R 193 229 -i 1.0 -l $IP_NO ${COL_MASS_K_NO} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/no_uv_l -m ${sp_dir}/no_uv_lm \
    -L ${sp_dir}/no_lbl_uv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/no_uv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/no_uv_log
  fi
fi

if [ ! -s $sp_dir/no_d1l_l ] ; then
  if [ ! -s $NO_UVLBL ] ; then
    echo "NO: No ultra-violet LBL file: please run ./mk_no_uvlbl_2000_earth"
    exit 1
  else
    echo "NO: UV d(1-0) - lines"
    rm -f $sp_dir/no_d1l_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 182 184 -l $IP_NO ${COL_MASS_K_NO} -b 5.0e-4 \
      -s $skelfile +S $SOLSPEC -lk \
      -o $sp_dir/no_d1l_l -m $sp_dir/no_d1l_lm \
      -L $NO_UVLBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/no_d1l_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/no_d1l_log
    fi
  fi
fi
if [ ! -s $sp_dir/no_d0l_l ] ; then
  if [ ! -s $NO_UVLBL ] ; then
    echo "NO: No ultra-violet LBL file: please run ./mk_no_uvlbl_2000_earth"
    exit 1
  else
    echo "NO: UV d(0-0) - lines"
    rm -f $sp_dir/no_d0l_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 190 192 -l $IP_NO ${COL_MASS_K_NO} -b 5.0e-4 \
      -s $skelfile +S $SOLSPEC -lk \
      -o $sp_dir/no_d0l_l -m $sp_dir/no_d0l_lm \
      -L $NO_UVLBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/no_d0l_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/no_d0l_log
    fi
  fi
fi

if [ ! -s $sp_dir/no_nir_l ] ; then
  if [ ! -s $NO_LBL ] ; then
    echo "NO: No LBL file: please run ./mk_no_lbl_2000_earth"
    exit 1
  else
    echo "NO: near infra-red"
    rm -f $sp_dir/no_nir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 413 1000 -l $IP_NO ${COL_MASS_K_NO} -b 5.0e-4 \
      -s $skelfile +S $SOLSPEC -lk \
      -o $sp_dir/no_nir_l -m $sp_dir/no_nir_lm \
      -L $NO_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/no_nir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/no_nir_log
    fi
  fi
fi
if [ ! -s $sp_dir/no_mir_l ] ; then
  if [ ! -s $NO_LBL ] ; then
    echo "NO: No LBL file: please run ./mk_no_lbl_2000_earth"
    exit 1
  else
    echo "NO: mid infra-red"
    rm -f $sp_dir/no_mir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1001 1500 -l $IP_NO ${COL_MASS_K_NO} -b 5.0e-4 \
      -s $skelfile -u -lk \
      -o $sp_dir/no_mir_l -m $sp_dir/no_mir_lm \
      -L $NO_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/no_mir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/no_mir_log
    fi
  fi
fi
if [ ! -s $sp_dir/no_fir_l ] ; then
  if [ ! -s $NO_LBL ] ; then
    echo "NO: No LBL file: please run ./mk_no_lbl_2000_earth"
    exit 1
  else
    echo "NO: far infra-red"
    rm -f $sp_dir/no_fir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1501 2000 -l $IP_NO ${COL_MASS_K_NO} -b 5.0e-4 \
      -s $skelfile -u -lk \
      -o $sp_dir/no_fir_l -m $sp_dir/no_fir_lm \
      -L $NO_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/no_fir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/no_fir_log
    fi
  fi
fi

# ----------------------------
# Sulfur dioxide (SO2)
# ----------------------------
uv_so2=${sp_dir}/so2.uvxsc
rm -f $uv_so2
dat2xsc so2_Feng99_Holland2005_ManattLane93.dat $uv_so2  #  4.7 - 403.7 nm
if [ ! -s ${sp_dir}/so2_xuv_l ] ; then
  echo 'SO2: XUV cross-section'
  rm -f ${sp_dir}/so2_xuv_l* ${sp_dir}/so2_lbl_xuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_so2 \
    -R 5 10 -i 1000.0 -l $IP_SO2 ${COL_MASS_K_SO2} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/so2_xuv_l -m ${sp_dir}/so2_xuv_lm \
    -L ${sp_dir}/so2_lbl_xuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/so2_xuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/so2_xuv_log
  fi
fi
if [ ! -s ${sp_dir}/so2_euv_l ] ; then
  echo 'SO2: EUV cross-section'
  rm -f ${sp_dir}/so2_euv_l* ${sp_dir}/so2_lbl_euv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_so2 \
    -R 11 100 -i 10.0 -l $IP_SO2 ${COL_MASS_K_SO2} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/so2_euv_l -m ${sp_dir}/so2_euv_lm \
    -L ${sp_dir}/so2_lbl_euv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/so2_euv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/so2_euv_log
  fi
fi
if [ ! -s ${sp_dir}/so2_uv_l ] ; then
  echo 'SO2: UV cross-section'
  rm -f ${sp_dir}/so2_uv_l* ${sp_dir}/so2_lbl_uv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_so2 \
    -R 101 404 -i 1.0 -l $IP_SO2 ${COL_MASS_K_SO2} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/so2_uv_l -m ${sp_dir}/so2_uv_lm \
    -L ${sp_dir}/so2_lbl_uv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/so2_uv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/so2_uv_log
  fi
fi

if [ ! -s $sp_dir/so2_fir_l ] ; then
  if [ ! -s $SO2_LBL ] ; then
    echo "SO2: No LBL file: please run ./mk_so2_lbl_2000_earth"
    exit 1
  else
    echo "SO2: far infra-red"
    rm -f $sp_dir/so2_fir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1535 2000 -l $IP_SO2 ${COL_MASS_K_SO2} -b 5.0e-4 \
      -s $skelfile -u -lk \
      -o $sp_dir/so2_fir_l -m $sp_dir/so2_fir_lm \
      -L $SO2_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/so2_fir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/so2_fir_log
    fi
  fi
fi

# ----------------------------
# Nitrogen Dioxide (NO2)
# ----------------------------
uv_no2=${sp_dir}/no2_220-294K.uvxsc  #  6.2 - 666.6 nm
no2_pt_file="pt_no2"

if [ ! -s $uv_no2 ] ; then
  rm -f no2_???K.uvxsc
  dat2xsc -t 220 no2_220K_Adams2026.dat no2_220K.uvxsc
  dat2xsc -t 294 no2_294K_Adams2026.dat no2_294K.uvxsc
  cat no2_220K.uvxsc no2_294K.uvxsc > $uv_no2
  rm -f no2_???K.uvxsc
fi

if [ ! -s ${sp_dir}/no2_xuv_l ] ; then
  echo 'NO2: XUV cross-section'
  rm -f ${sp_dir}/no2_xuv_l* ${sp_dir}/no2_lbl_xuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_no2 \
    -R 7 10 -i 1000.0 -l $IP_NO2 ${COL_MASS_K_NO2} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/no2_xuv_l -m ${sp_dir}/no2_xuv_lm \
    -L ${sp_dir}/no2_lbl_xuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/no2_xuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/no2_xuv_log
  fi
fi
if [ ! -s ${sp_dir}/no2_euv_l ] ; then
  echo 'NO2: EUV cross-section'
  rm -f ${sp_dir}/no2_euv_l* ${sp_dir}/no2_lbl_euv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_no2 \
    -R 11 100 -i 10.0 -l $IP_NO2 ${COL_MASS_K_NO2} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/no2_euv_l -m ${sp_dir}/no2_euv_lm \
    -L ${sp_dir}/no2_lbl_euv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/no2_euv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/no2_euv_log
  fi
fi
if [ ! -s ${sp_dir}/no2_fuv_l ] ; then
  echo 'NO2: FUV cross-section'
  rm -f ${sp_dir}/no2_fuv_l* ${sp_dir}/no2_lbl_fuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_no2 \
    -R 101 238 -i 1.0 -l $IP_NO2 ${COL_MASS_K_NO2} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/no2_fuv_l -m ${sp_dir}/no2_fuv_lm \
    -L ${sp_dir}/no2_lbl_fuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/no2_fuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/no2_fuv_log
  fi
fi
if [ ! -s ${sp_dir}/no2_uv_l ] ; then
  echo 'NO2: UV cross-section'
  rm -f ${sp_dir}/no2_uv_l* ${sp_dir}/no2_lbl_uv*
  ck_args="Ccorr_k -F $no2_pt_file -UVX $uv_no2 \
    -R 239 667 -i 1.0 -l $IP_NO2 ${COL_MASS_K_NO2} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -lk \
    -o ${sp_dir}/no2_uv_l -m ${sp_dir}/no2_uv_lm \
    -L ${sp_dir}/no2_lbl_uv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/no2_uv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/no2_uv_log
  fi
fi

# ----------------------------
# Ammonia (NH3)
# ----------------------------
uv_nh3=${sp_dir}/nh3.uvxsc
rm -f $uv_nh3
dat2xsc --offset nh3_Venot2012.dat $uv_nh3  #  7.5 - 229.5 nm
if [ ! -s ${sp_dir}/nh3_xuv_l ] ; then
  echo 'NH3: XUV cross-section'
  rm -f ${sp_dir}/nh3_xuv_l* ${sp_dir}/nh3_lbl_xuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_nh3 \
    -R 8 10 -i 1000.0 -l $IP_NH3 ${COL_MASS_K_NH3} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/nh3_xuv_l -m ${sp_dir}/nh3_xuv_lm \
    -L ${sp_dir}/nh3_lbl_xuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/nh3_xuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/nh3_xuv_log
  fi
fi
if [ ! -s ${sp_dir}/nh3_euv_l ] ; then
  echo 'NH3: EUV cross-section'
  rm -f ${sp_dir}/nh3_euv_l* ${sp_dir}/nh3_lbl_euv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_nh3 \
    -R 11 100 -i 10.0 -l $IP_NH3 ${COL_MASS_K_NH3} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/nh3_euv_l -m ${sp_dir}/nh3_euv_lm \
    -L ${sp_dir}/nh3_lbl_euv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/nh3_euv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/nh3_euv_log
  fi
fi
if [ ! -s ${sp_dir}/nh3_fuv_l ] ; then
  echo 'NH3: FUV cross-section'
  rm -f ${sp_dir}/nh3_fuv_l* ${sp_dir}/nh3_lbl_fuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_nh3 \
    -R 101 230 -i 1.0 -l $IP_NH3 ${COL_MASS_K_NH3} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/nh3_fuv_l -m ${sp_dir}/nh3_fuv_lm \
    -L ${sp_dir}/nh3_lbl_fuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/nh3_fuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/nh3_fuv_log
  fi
fi

# ----------------------------
# Nitric Acid (HNO3)
# ----------------------------
uv_hno3=${sp_dir}/hno3_200-315K.uvxsc  #  105 - 350 nm
hno3_pt_file="pt_hno3"

if [ ! -s $uv_hno3 ] ; then
  rm -f hno3_???K.dat hno3_???K.uvxsc
  calc_hno3_xsc
  dat2xsc -t 200 hno3_200K.dat hno3_200K.uvxsc
  dat2xsc -t 220 hno3_220K.dat hno3_220K.uvxsc
  dat2xsc -t 240 hno3_240K_Burkholder93.dat hno3_240K.uvxsc
  dat2xsc -t 260 hno3_260K_Burkholder93.dat hno3_260K.uvxsc
  dat2xsc -t 280 hno3_280K_Burkholder93.dat hno3_280K.uvxsc
  dat2xsc -t 298 hno3_298K_SutuLee84_Burkholder93.dat hno3_298K.uvxsc
  dat2xsc -t 315 hno3_315K_Burkholder93.dat hno3_315K.uvxsc
  cat hno3_200K.uvxsc hno3_220K.uvxsc hno3_240K.uvxsc hno3_260K.uvxsc \
      hno3_280K.uvxsc hno3_298K.uvxsc hno3_315K.uvxsc > $uv_hno3
  rm -f hno3_???K.dat hno3_???K.uvxsc
fi

if [ ! -s ${sp_dir}/hno3_uv_l ] ; then
  echo 'HNO3: UV cross-section'
  rm -f ${sp_dir}/hno3_uv_l* ${sp_dir}/hno3_lbl_uv*
  ck_args="Ccorr_k -F $hno3_pt_file -UVX $uv_hno3 \
    -R 105 351 -i 1.0 -l $IP_HNO3 ${COL_MASS_K_HNO3} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -lk \
    -o ${sp_dir}/hno3_uv_l -m ${sp_dir}/hno3_uv_lm \
    -L ${sp_dir}/hno3_lbl_uv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/hno3_uv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/hno3_uv_log
  fi
fi

# ----------------------------
# Nitrogen (N2)
# ----------------------------
uv_n2=${sp_dir}/n2.uvxsc
rm -f $uv_n2
dat2xsc n2_Manners2024.dat $uv_n2  #  0.04 - 98.6 nm
if [ ! -s ${sp_dir}/n2_xuv_l ] ; then
  echo 'N2: XUV cross-section'
  rm -f ${sp_dir}/n2_xuv_l* ${sp_dir}/n2_lbl_xuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_n2 \
    -R 1 10 -i 1000.0 -l $IP_N2 ${COL_MASS_K_N2} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/n2_xuv_l -m ${sp_dir}/n2_xuv_lm \
    -L ${sp_dir}/n2_lbl_xuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/n2_xuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/n2_xuv_log
  fi
fi
if [ ! -s ${sp_dir}/n2_euv_l ] ; then
  echo 'N2: EUV cross-section'
  rm -f ${sp_dir}/n2_euv_l* ${sp_dir}/n2_lbl_euv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_n2 \
    -R 11 99 -i 10.0 -l $IP_N2 ${COL_MASS_K_N2} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/n2_euv_l -m ${sp_dir}/n2_euv_lm \
    -L ${sp_dir}/n2_lbl_euv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/n2_euv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/n2_euv_log
  fi
fi

# ----------------------------
# CFC-11 (CCl3F)
# ----------------------------
if [ ! -s ${sp_dir}/cfc11_ir_l ] ; then
  echo "CFC-11 (CCl3F)"
  rm -f ${sp_dir}/cfc11_ir_l* ${sp_dir}/cfc11_lbl_ir*
  ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} -X ${HITRAN_CFC11} \
    -R 1872 1929 -i 1.0 -l $IP_CFC11 ${COL_MASS_K_CFC11} -t 1.0e-4 \
    -s $skelfile -u -lk \
    -o ${sp_dir}/cfc11_ir_l -m ${sp_dir}/cfc11_ir_lm \
    -L ${sp_dir}/cfc11_lbl_ir.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/cfc11_ir_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/cfc11_ir_log
  fi
fi

# ----------------------------
# CFC-12 (CCl2F2)
# ----------------------------
if [ ! -s ${sp_dir}/cfc12_ir_l ] ; then
  echo "CFC-12 (CCl2F2)"
  rm -f ${sp_dir}/cfc12_ir_l* ${sp_dir}/cfc12_lbl_ir*
  ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} -X ${HITRAN_CFC12} \
    -R 1873 1921 -i 1.0 -l $IP_CFC12 ${COL_MASS_K_CFC12} -t 1.0e-4 \
    -s $skelfile -u -lk \
    -o ${sp_dir}/cfc12_ir_l -m ${sp_dir}/cfc12_ir_lm \
    -L ${sp_dir}/cfc12_lbl_ir.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/cfc12_ir_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/cfc12_ir_log
  fi
fi

# ----------------------------
# CFC-113 (C2Cl3F3)
# ----------------------------
cfc113_pt_file="pt_cfc113"
if [ ! -s ${sp_dir}/cfc113_ir_l ] ; then
  echo "CFC-113 (C2Cl3F3)"
  rm -f ${sp_dir}/cfc113_ir_l* ${sp_dir}/cfc113_lbl_ir*
  ck_args="Ccorr_k -F $cfc113_pt_file -X ${HITRAN_CFC113} \
    -R 1876 1940 -i 1.0 -l $IP_CFC113 ${COL_MASS_K_CFC113} -t 1.0e-4 \
    -s $skelfile -u -lk \
    -o ${sp_dir}/cfc113_ir_l -m ${sp_dir}/cfc113_ir_lm \
    -L ${sp_dir}/cfc113_lbl_ir.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/cfc113_ir_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/cfc113_ir_log
  fi
fi

# ----------------------------
# HCFC-22 (CHClF2)
# ----------------------------
if [ ! -s ${sp_dir}/hcfc22_ir_l ] ; then
  echo "HCFC-22 (CHClF2)"
  rm -f ${sp_dir}/hcfc22_ir_l* ${sp_dir}/hcfc22_lbl_ir*
  ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} -X ${HITRAN_HCFC22} \
    -R 1863 1927 -i 1.0 -l $IP_HCFC22 ${COL_MASS_K_HCFC22} -t 1.0e-4 \
    -s $skelfile -u -lk \
    -o ${sp_dir}/hcfc22_ir_l -m ${sp_dir}/hcfc22_ir_lm \
    -L ${sp_dir}/hcfc22_lbl_ir.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/hcfc22_ir_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/hcfc22_ir_log
  fi
fi

# ----------------------------
# HFC-134a (CFH2CF3)
# ----------------------------
if [ ! -s ${sp_dir}/hfc134a_ir_l ] ; then
  echo "HFC-134a (CFH2CF3)"
  rm -f ${sp_dir}/hfc134a_ir_l* ${sp_dir}/hfc134a_lbl_ir*
  ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} -X ${HITRAN_HFC134A} \
    -R 1840 1925 -i 1.0 -l $IP_HFC134A ${COL_MASS_K_HFC134A} -t 1.0e-4 \
    -s $skelfile -u -lk \
    -o ${sp_dir}/hfc134a_ir_l -m ${sp_dir}/hfc134a_ir_lm \
    -L ${sp_dir}/hfc134a_lbl_ir.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/hfc134a_ir_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/hfc134a_ir_log
  fi
fi

# ----------------------------
# Carbonyl Sulphide (OCS)
# ----------------------------
uv_ocs=${sp_dir}/ocs_225-295K.uvxsc  #  186 - 292 nm
ocs_pt_file="pt_ocs"

if [ ! -s $uv_ocs ] ; then
  rm -f ocs_???K.uvxsc
  dat2xsc -t 225 ocs_225K_JPL2010.dat ocs_225K.uvxsc
  dat2xsc -t 295 ocs_295K_JPL2010.dat ocs_295K.uvxsc
  cat ocs_225K.uvxsc ocs_295K.uvxsc > $uv_ocs
  rm -f ocs_???K.uvxsc
fi

if [ ! -s ${sp_dir}/ocs_uv_l ] ; then
  echo 'OCS: UV cross-section'
  rm -f ${sp_dir}/ocs_uv_l* ${sp_dir}/ocs_lbl_uv*
  ck_args="Ccorr_k -F $ocs_pt_file -UVX $uv_ocs \
    -R 186 293 -i 1.0 -l $IP_OCS ${COL_MASS_K_OCS} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -lk \
    -o ${sp_dir}/ocs_uv_l -m ${sp_dir}/ocs_uv_lm \
    -L ${sp_dir}/ocs_lbl_uv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/ocs_uv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/ocs_uv_log
  fi
fi

if [ ! -s $sp_dir/ocs_nir_l ] ; then
  if [ ! -s $OCS_LBL ] ; then
    echo "OCS: No LBL file: please run ./mk_ocs_lbl_2000_earth"
    exit 1
  else
    echo "OCS: near infra-red"
    rm -f $sp_dir/ocs_nir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 691 1000 -l $IP_OCS ${COL_MASS_K_OCS} -b 5.0e-4 \
      -s $skelfile +S $SOLSPEC -lk \
      -o $sp_dir/ocs_nir_l -m $sp_dir/ocs_nir_lm \
      -L $OCS_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/ocs_nir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/ocs_nir_log
    fi
  fi
fi
if [ ! -s $sp_dir/ocs_mir_l ] ; then
  if [ ! -s $OCS_LBL ] ; then
    echo "OCS: No LBL file: please run ./mk_ocs_lbl_2000_earth"
    exit 1
  else
    echo "OCS: mid infra-red"
    rm -f $sp_dir/ocs_mir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1001 1500 -l $IP_OCS ${COL_MASS_K_OCS} -b 5.0e-4 \
      -s $skelfile -u -lk \
      -o $sp_dir/ocs_mir_l -m $sp_dir/ocs_mir_lm \
      -L $OCS_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/ocs_mir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/ocs_mir_log
    fi
  fi
fi
if [ ! -s $sp_dir/ocs_fir_l ] ; then
  if [ ! -s $OCS_LBL ] ; then
    echo "OCS: No LBL file: please run ./mk_ocs_lbl_2000_earth"
    exit 1
  else
    echo "OCS: far infra-red"
    rm -f $sp_dir/ocs_fir_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1501 2000 -l $IP_OCS ${COL_MASS_K_OCS} -b 5.0e-4 \
      -s $skelfile -u -lk \
      -o $sp_dir/ocs_fir_l -m $sp_dir/ocs_fir_lm \
      -L $OCS_LBL -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/ocs_fir_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/ocs_fir_log
    fi
  fi
fi

# ----------------------------
# Acetylene (C2H2)
# ----------------------------
uv_c2h2=${sp_dir}/c2h2.uvxsc
rm -f $uv_c2h2
dat2xsc --offset c2h2_Venot2012.dat $uv_c2h2  #  7.5 - 228.5 nm
if [ ! -s ${sp_dir}/c2h2_xuv_l ] ; then
  echo 'C2H2: XUV cross-section'
  rm -f ${sp_dir}/c2h2_xuv_l* ${sp_dir}/c2h2_lbl_xuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_c2h2 \
    -R 8 10 -i 1000.0 -l $IP_C2H2 ${COL_MASS_K_C2H2} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/c2h2_xuv_l -m ${sp_dir}/c2h2_xuv_lm \
    -L ${sp_dir}/c2h2_lbl_xuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/c2h2_xuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/c2h2_xuv_log
  fi
fi
if [ ! -s ${sp_dir}/c2h2_euv_l ] ; then
  echo 'C2H2: EUV cross-section'
  rm -f ${sp_dir}/c2h2_euv_l* ${sp_dir}/c2h2_lbl_euv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_c2h2 \
    -R 11 100 -i 10.0 -l $IP_C2H2 ${COL_MASS_K_C2H2} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/c2h2_euv_l -m ${sp_dir}/c2h2_euv_lm \
    -L ${sp_dir}/c2h2_lbl_euv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/c2h2_euv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/c2h2_euv_log
  fi
fi
if [ ! -s ${sp_dir}/c2h2_fuv_l ] ; then
  echo 'C2H2: FUV cross-section'
  rm -f ${sp_dir}/c2h2_fuv_l* ${sp_dir}/c2h2_lbl_fuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_c2h2 \
    -R 101 229 -i 1.0 -l $IP_C2H2 ${COL_MASS_K_C2H2} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/c2h2_fuv_l -m ${sp_dir}/c2h2_fuv_lm \
    -L ${sp_dir}/c2h2_lbl_fuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/c2h2_fuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/c2h2_fuv_log
  fi
fi

# ----------------------------
# Hydrogen Cynanide (HCN)
# ----------------------------
uv_hcn=${sp_dir}/hcn.uvxsc
rm -f $uv_hcn
dat2xsc --offset hcn_Venot2012.dat $uv_hcn  #  80.5 - 184.5 nm
if [ ! -s ${sp_dir}/hcn_euv_l ] ; then
  echo 'HCN: EUV cross-section'
  rm -f ${sp_dir}/hcn_euv_l* ${sp_dir}/hcn_lbl_euv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_hcn \
    -R 81 100 -i 10.0 -l $IP_HCN ${COL_MASS_K_HCN} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/hcn_euv_l -m ${sp_dir}/hcn_euv_lm \
    -L ${sp_dir}/hcn_lbl_euv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/hcn_euv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/hcn_euv_log
  fi
fi
if [ ! -s ${sp_dir}/hcn_fuv_l ] ; then
  echo 'HCN: FUV cross-section'
  rm -f ${sp_dir}/hcn_fuv_l* ${sp_dir}/hcn_lbl_fuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_hcn \
    -R 101 185 -i 1.0 -l $IP_HCN ${COL_MASS_K_HCN} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/hcn_fuv_l -m ${sp_dir}/hcn_fuv_lm \
    -L ${sp_dir}/hcn_lbl_fuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/hcn_fuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/hcn_fuv_log
  fi
fi

# ----------------------------
# Atomic Oxygen (O)
# ----------------------------
uv_o=${sp_dir}/o.uvxsc
rm -f $uv_o
dat2xsc o_Manners2024.dat $uv_o  #  0.04 - 102.7 nm
if [ ! -s ${sp_dir}/o_xuv_l ] ; then
  echo 'O: XUV cross-section'
  rm -f ${sp_dir}/o_xuv_l* ${sp_dir}/o_lbl_xuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_o \
    -R 1 10 -i 1000.0 -l $IP_O ${COL_MASS_K_O} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/o_xuv_l -m ${sp_dir}/o_xuv_lm \
    -L ${sp_dir}/o_lbl_xuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/o_xuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/o_xuv_log
  fi
fi
if [ ! -s ${sp_dir}/o_euv_l ] ; then
  echo 'O: EUV cross-section'
  rm -f ${sp_dir}/o_euv_l* ${sp_dir}/o_lbl_euv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_o \
    -R 11 93 -i 10.0 -l $IP_O ${COL_MASS_K_O} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/o_euv_l -m ${sp_dir}/o_euv_lm \
    -L ${sp_dir}/o_lbl_euv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/o_euv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/o_euv_log
  fi
fi

# ----------------------------
# Atomic Nitrogen (N)
# ----------------------------
uv_n=${sp_dir}/n.uvxsc
rm -f $uv_n
dat2xsc n_Manners2024.dat $uv_n  #  0.04 - 102.7 nm
if [ ! -s ${sp_dir}/n_xuv_l ] ; then
  echo 'N: XUV cross-section'
  rm -f ${sp_dir}/n_xuv_l* ${sp_dir}/n_lbl_xuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_n \
    -R 1 10 -i 1000.0 -l $IP_N ${COL_MASS_K_N} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/n_xuv_l -m ${sp_dir}/n_xuv_lm \
    -L ${sp_dir}/n_lbl_xuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/n_xuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/n_xuv_log
  fi
fi
if [ ! -s ${sp_dir}/n_euv_l ] ; then
  echo 'N: EUV cross-section'
  rm -f ${sp_dir}/n_euv_l* ${sp_dir}/n_lbl_euv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_n \
    -R 11 86 -i 10.0 -l $IP_N ${COL_MASS_K_N} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/n_euv_l -m ${sp_dir}/n_euv_lm \
    -L ${sp_dir}/n_lbl_euv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/n_euv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/n_euv_log
  fi
fi

# ----------------------------
# Nitrogen Trioxide (NO3)
# ----------------------------
vis_no3=${sp_dir}/no3.uvxsc
rm -f $vis_no3
dat2xsc no3_298K_JPL2010.dat $vis_no3  #  403 - 691 nm
if [ ! -s ${sp_dir}/no3_vis_l ] ; then
  echo 'NO3: Visible cross-section'
  rm -f ${sp_dir}/no3_vis_l* ${sp_dir}/no3_lbl_vis*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $vis_no3 \
    -R 403 692 -i 1.0 -l $IP_NO3 ${COL_MASS_K_NO3} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/no3_vis_l -m ${sp_dir}/no3_vis_lm \
    -L ${sp_dir}/no3_lbl_vis.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/no3_vis_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/no3_vis_log
  fi
fi

# ----------------------------
# Dinitrogen Pentoxide (N2O5)
# ----------------------------
uv_n2o5=${sp_dir}/n2o5_233-295K.uvxsc  #  152 - 420 nm
n2o5_pt_file="pt_n2o5"

if [ ! -s $uv_n2o5 ] ; then
  rm -f n2o5_???K.dat n2o5_???K.uvxsc
  calc_n2o5_xsc
  dat2xsc -t 233 n2o5_233K.dat n2o5_233K.uvxsc
  dat2xsc -t 255 n2o5_255K.dat n2o5_255K.uvxsc
  dat2xsc -t 275 n2o5_275K.dat n2o5_275K.uvxsc
  dat2xsc -t 295 n2o5_295K.dat n2o5_295K.uvxsc
  cat n2o5_233K.uvxsc n2o5_255K.uvxsc \
      n2o5_275K.uvxsc n2o5_295K.uvxsc > $uv_n2o5
  rm -f n2o5_???K.dat n2o5_???K.uvxsc
fi

if [ ! -s ${sp_dir}/n2o5_uv_l ] ; then
  echo 'N2O5: UV cross-section'
  rm -f ${sp_dir}/n2o5_uv_l* ${sp_dir}/n2o5_lbl_uv*
  ck_args="Ccorr_k -F $n2o5_pt_file -UVX $uv_n2o5 \
    -R 152 421 -i 1.0 -l $IP_N2O5 ${COL_MASS_K_N2O5} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -lk \
    -o ${sp_dir}/n2o5_uv_l -m ${sp_dir}/n2o5_uv_lm \
    -L ${sp_dir}/n2o5_lbl_uv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/n2o5_uv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/n2o5_uv_log
  fi
fi

# ----------------------------
# Nitrous Acid (HONO)
# ----------------------------
uv_hono=${sp_dir}/hono.uvxsc
rm -f $uv_hono
dat2xsc hono_298K_JPL2010_Stutz2000.dat $uv_hono  #  184 - 400.5 nm
if [ ! -s ${sp_dir}/hono_uv_l ] ; then
  echo 'HONO: UV cross-section'
  rm -f ${sp_dir}/hono_uv_l* ${sp_dir}/hono_lbl_uv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_hono \
    -R 184 401 -i 1.0 -l $IP_HONO ${COL_MASS_K_HONO} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/hono_uv_l -m ${sp_dir}/hono_uv_lm \
    -L ${sp_dir}/hono_lbl_uv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/hono_uv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/hono_uv_log
  fi
fi

# ----------------------------
# Peroxynitric Acid (HO2NO2)
# ----------------------------
uv_ho2no2=${sp_dir}/ho2no2.uvxsc
rm -f $uv_ho2no2
dat2xsc ho2no2_298K_JPL2015.dat $uv_ho2no2  #  190 - 350 nm
if [ ! -s ${sp_dir}/ho2no2_uv_l ] ; then
  echo 'HO2NO2: UV cross-section'
  rm -f ${sp_dir}/ho2no2_uv_l* ${sp_dir}/ho2no2_lbl_uv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_ho2no2 \
    -R 190 351 -i 1.0 -l $IP_HO2NO2 ${COL_MASS_K_HO2NO2} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/ho2no2_uv_l -m ${sp_dir}/ho2no2_uv_lm \
    -L ${sp_dir}/ho2no2_lbl_uv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/ho2no2_uv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/ho2no2_uv_log
  fi
fi

# ----------------------------
# Hydrogen Peroxide (H2O2)
# ----------------------------
uv_h2o2=${sp_dir}/h2o2_200-320K.uvxsc  #  106 - 410 nm
h2o2_pt_file="pt_h2o2"

if [ ! -s $uv_h2o2 ] ; then
  rm -f h2o2_???K.dat h2o2_???K.uvxsc h2o2_298K_SutoLee83_Kahan2012.dat
  calc_h2o2_xsc
  cat h2o2_SutoLee83_106-190nm.dat h2o2_298K.dat \
      h2o2_Kahan2012_353-410nm.dat > h2o2_298K_SutoLee83_Kahan2012.dat
  dat2xsc -t 200 h2o2_200K.dat h2o2_200K.uvxsc
  dat2xsc -t 220 h2o2_220K.dat h2o2_220K.uvxsc
  dat2xsc -t 240 h2o2_240K.dat h2o2_240K.uvxsc
  dat2xsc -t 260 h2o2_260K.dat h2o2_260K.uvxsc
  dat2xsc -t 280 h2o2_280K.dat h2o2_280K.uvxsc
  dat2xsc -t 298 h2o2_298K_SutoLee83_Kahan2012.dat h2o2_298K.uvxsc
  dat2xsc -t 320 h2o2_320K.dat h2o2_320K.uvxsc
  cat h2o2_???K.uvxsc > $uv_h2o2
  rm -f h2o2_???K.dat h2o2_???K.uvxsc h2o2_298K_SutoLee83_Kahan2012.dat
fi

if [ ! -s ${sp_dir}/h2o2_fuv_l ] ; then
  echo 'H2O2: Far-UV cross-section'
  rm -f ${sp_dir}/h2o2_fuv_l* ${sp_dir}/h2o2_lbl_fuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_h2o2 \
    -R 106 189 -i 1.0 -l $IP_H2O2 ${COL_MASS_K_H2O2} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/h2o2_fuv_l -m ${sp_dir}/h2o2_fuv_lm \
    -L ${sp_dir}/h2o2_lbl_fuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/h2o2_fuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/h2o2_fuv_log
  fi
fi
if [ ! -s ${sp_dir}/h2o2_uv_l ] ; then
  echo 'H2O2: UV cross-section'
  rm -f ${sp_dir}/h2o2_uv_l* ${sp_dir}/h2o2_lbl_uv*
  ck_args="Ccorr_k -F $h2o2_pt_file -UVX $uv_h2o2 \
    -R 190 352 -i 1.0 -l $IP_H2O2 ${COL_MASS_K_H2O2} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -lk \
    -o ${sp_dir}/h2o2_uv_l -m ${sp_dir}/h2o2_uv_lm \
    -L ${sp_dir}/h2o2_lbl_uv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/h2o2_uv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/h2o2_uv_log
  fi
fi
if [ ! -s ${sp_dir}/h2o2_nuv_l ] ; then
  echo 'H2O2: Near-UV cross-section'
  rm -f ${sp_dir}/h2o2_nuv_l* ${sp_dir}/h2o2_lbl_nuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_h2o2 \
    -R 353 411 -i 1.0 -l $IP_H2O2 ${COL_MASS_K_H2O2} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/h2o2_nuv_l -m ${sp_dir}/h2o2_nuv_lm \
    -L ${sp_dir}/h2o2_lbl_nuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/h2o2_nuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/h2o2_nuv_log
  fi
fi

# ----------------------------
# Ethane (C2H6)
# ----------------------------
uv_c2h6=${sp_dir}/c2h6.uvxsc
rm -f $uv_c2h6
dat2xsc --offset c2h6_Venot2012.dat $uv_c2h6  #  6.5 - 159.5 nm
if [ ! -s ${sp_dir}/c2h6_xuv_l ] ; then
  echo 'C2H6: XUV cross-section'
  rm -f ${sp_dir}/c2h6_xuv_l* ${sp_dir}/c2h6_lbl_xuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_c2h6 \
    -R 7 10 -i 1000.0 -l $IP_C2H6 ${COL_MASS_K_C2H6} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/c2h6_xuv_l -m ${sp_dir}/c2h6_xuv_lm \
    -L ${sp_dir}/c2h6_lbl_xuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/c2h6_xuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/c2h6_xuv_log
  fi
fi
if [ ! -s ${sp_dir}/c2h6_euv_l ] ; then
  echo 'C2H6: EUV cross-section'
  rm -f ${sp_dir}/c2h6_euv_l* ${sp_dir}/c2h6_lbl_euv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_c2h6 \
    -R 11 100 -i 10.0 -l $IP_C2H6 ${COL_MASS_K_C2H6} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/c2h6_euv_l -m ${sp_dir}/c2h6_euv_lm \
    -L ${sp_dir}/c2h6_lbl_euv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/c2h6_euv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/c2h6_euv_log
  fi
fi
if [ ! -s ${sp_dir}/c2h6_fuv_l ] ; then
  echo 'C2H6: FUV cross-section'
  rm -f ${sp_dir}/c2h6_fuv_l* ${sp_dir}/c2h6_lbl_fuv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_c2h6 \
    -R 101 160 -i 1.0 -l $IP_C2H6 ${COL_MASS_K_C2H6} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/c2h6_fuv_l -m ${sp_dir}/c2h6_fuv_lm \
    -L ${sp_dir}/c2h6_lbl_fuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/c2h6_fuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/c2h6_fuv_log
  fi
fi

# ----------------------------
# Methyl Radical (CH3)
# ----------------------------
uv_ch3=${sp_dir}/ch3.uvxsc
rm -f $uv_ch3
dat2xsc ch3_298K_Cameron2002.dat $uv_ch3  #  200 - 240 nm
if [ ! -s ${sp_dir}/ch3_uv_l ] ; then
  echo 'CH3: UV cross-section'
  rm -f ${sp_dir}/ch3_uv_l* ${sp_dir}/ch3_lbl_uv*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $uv_ch3 \
    -R 201 240 -i 1.0 -l $IP_CH3 ${COL_MASS_K_CH3} -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/ch3_uv_l -m ${sp_dir}/ch3_uv_lm \
    -L ${sp_dir}/ch3_lbl_uv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/ch3_uv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/ch3_uv_log
  fi
fi


##########################################################################
#################### got to here #########################################
wait

# Create the spectral file from the data calculated above
# -------------------------------------------------------
echo 'Constructing spectral file'
mv ${specfile} ${specfile}_old 2> /dev/null
mv ${specfile}_k ${specfile}_old_k 2> /dev/null
prep_spec << EOF > ${specfile}_log1 2>&1
$skelfile
n
$specfile
2
n
${SOLSPEC}
n
3
a
5
${sp_dir}/h2o_xuv_l
5
y
${sp_dir}/h2o_euv_l
5
y
${sp_dir}/h2o_fuv_l
5
y
${sp_dir}/h2o_nuv_l
5
y
${sp_dir}/h2o_vis_l
5
y
${sp_dir}/h2o_nirf_l
5
y
${sp_dir}/h2o_mirf_l
5
y
${sp_dir}/h2o_firf_l
9
${sp_dir}/h2o_nir_s
9
y
${sp_dir}/h2o_mir_s
9
y
${sp_dir}/h2o_fir_s
5
y
${sp_dir}/co2_xuv_l
5
y
${sp_dir}/co2_euv_l
5
y
${sp_dir}/co2_fuv_l
5
y
${sp_dir}/co2_nir_l
5
y
${sp_dir}/co2_mir_l
5
y
${sp_dir}/co2_fir_l
5
y
${sp_dir}/o3_uv_l
5
y
${sp_dir}/o3_mir_l
5
y
${sp_dir}/o3_fir_l
5
y
${sp_dir}/n2o_xuv_l
5
y
${sp_dir}/n2o_euv_l
5
y
${sp_dir}/n2o_fuv_l
5
y
${sp_dir}/n2o_uv_l
5
y
${sp_dir}/n2o_nir_l
5
y
${sp_dir}/n2o_mir_l
5
y
${sp_dir}/n2o_fir_l
5
y
${sp_dir}/co_xuv_l
5
y
${sp_dir}/co_euv_l
5
y
${sp_dir}/co_fuv_l
5
y
${sp_dir}/co_nir_l
5
y
${sp_dir}/co_mir_l
5
y
${sp_dir}/co_fir_l
5
y
${sp_dir}/ch4_xuv_l
5
y
${sp_dir}/ch4_euv_l
5
y
${sp_dir}/ch4_fuv_l
5
y
${sp_dir}/ch4_nir_l
5
y
${sp_dir}/ch4_mir_l
5
y
${sp_dir}/ch4_fir_l
5
y
${sp_dir}/o2_xuv_l
5
y
${sp_dir}/o2_euv_l
5
y
${sp_dir}/o2_fuv_l
5
y
${sp_dir}/o2_duv_l
5
y
${sp_dir}/o2_uv_l
5
y
${sp_dir}/o2_d1l_l
5
y
${sp_dir}/o2_d0l_l
5
y
${sp_dir}/o2_nir_l
5
y
${sp_dir}/o2_mir_l
5
y
${sp_dir}/o2_fir_l
5
y
${sp_dir}/no_xuv_l
5
y
${sp_dir}/no_euv_l
5
y
${sp_dir}/no_fuv_l
5
y
${sp_dir}/no_duv_l
5
y
${sp_dir}/no_uv_l
5
y
${sp_dir}/no_d1l_l
5
y
${sp_dir}/no_d0l_l
5
y
${sp_dir}/no_nir_l
5
y
${sp_dir}/no_mir_l
5
y
${sp_dir}/no_fir_l
5
y
${sp_dir}/so2_xuv_l
5
y
${sp_dir}/so2_euv_l
5
y
${sp_dir}/so2_uv_l
5
y
${sp_dir}/so2_fir_l
5
y
${sp_dir}/no2_xuv_l
5
y
${sp_dir}/no2_euv_l
5
y
${sp_dir}/no2_fuv_l
5
y
${sp_dir}/no2_uv_l
5
y
${sp_dir}/nh3_xuv_l
5
y
${sp_dir}/nh3_euv_l
5
y
${sp_dir}/nh3_fuv_l
5
y
${sp_dir}/hno3_uv_l
5
y
${sp_dir}/n2_xuv_l
5
y
${sp_dir}/n2_euv_l
5
y
${sp_dir}/cfc11_ir_l
5
y
${sp_dir}/cfc12_ir_l
5
y
${sp_dir}/cfc113_ir_l
5
y
${sp_dir}/hcfc22_ir_l
5
y
${sp_dir}/hfc134a_ir_l
5
y
${sp_dir}/ocs_uv_l
5
y
${sp_dir}/ocs_nir_l
5
y
${sp_dir}/ocs_mir_l
5
y
${sp_dir}/ocs_fir_l
5
y
${sp_dir}/c2h2_xuv_l
5
y
${sp_dir}/c2h2_euv_l
5
y
${sp_dir}/c2h2_fuv_l
5
y
${sp_dir}/hcn_euv_l
5
y
${sp_dir}/hcn_fuv_l
5
y
${sp_dir}/o_xuv_l
5
y
${sp_dir}/o_euv_l
5
y
${sp_dir}/n_xuv_l
5
y
${sp_dir}/n_euv_l
5
y
${sp_dir}/no3_vis_l
5
y
${sp_dir}/n2o5_uv_l
5
y
${sp_dir}/hono_uv_l
5
y
${sp_dir}/ho2no2_uv_l
5
y
${sp_dir}/h2o2_fuv_l
5
y
${sp_dir}/h2o2_uv_l
5
y
${sp_dir}/h2o2_nuv_l
5
y
${sp_dir}/c2h6_xuv_l
5
y
${sp_dir}/c2h6_euv_l
5
y
${sp_dir}/c2h6_fuv_l
5
y
${sp_dir}/ch3_uv_l
-1
EOF

exit 0
##########################################################################
##########################################################################

#Methanal (H2CO)
UV_H2CO='h2co.uvxsc' #   226nm - 370 nm
h2co_pt_file='pt_h2co'
if [ ! -s ${sp_dir}/h2co_xuv_l ] || [ ! -s ${sp_dir}/h2co_lbl_xuv.nc ] ; then
  echo 'H2CO (XUV)'
  rm -f ${sp_dir}/h2co_xuv_l*
  Ccorr_k -F $h2co_pt_file -UVX $UV_H2CO \
    -R 7 10 -i 1000.0 -l 48 2.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -q -r $REF_PT_FILE \
    -o ${sp_dir}/h2co_xuv_l -m ${sp_dir}/h2co_xuv_lm \
    -L ${sp_dir}/h2co_lbl_xuv.nc -np $procs \
     > ${sp_dir}/h2co_xuv_log
fi
if [ ! -s ${sp_dir}/h2co_euv_l ] || [ ! -s ${sp_dir}/h2co_lbl_euv.nc ] ; then
  echo 'H2CO (EUV)'
  rm -f ${sp_dir}/h2co_euv_l*
  Ccorr_k -F $h2co_pt_file -UVX $UV_H2CO \
    -R 11 100 -i 10.0 -l 48 2.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -q -r $REF_PT_FILE \
    -o ${sp_dir}/h2co_euv_l -m ${sp_dir}/h2co_euv_lm \
    -L ${sp_dir}/h2co_lbl_euv.nc -np $procs \
     > ${sp_dir}/h2co_euv_log
fi
if [ ! -s ${sp_dir}/h2co_uv_l ] || [ ! -s ${sp_dir}/h2co_lbl_uv.nc ] ; then
  echo 'H2CO (UV)'
  rm -f ${sp_dir}/h2co_uv_l*
  Ccorr_k -F $h2co_pt_file -UVX $UV_H2CO \
    -R 101 376 -i 1.0 -l 48 2.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -q -r $REF_PT_FILE \
    -o ${sp_dir}/h2co_uv_l -m ${sp_dir}/h2co_uv_lm \
    -L ${sp_dir}/h2co_lbl_uv.nc -np $procs \
     > ${sp_dir}/h2co_uv_log
fi

#Acetaldehyde (CH3CHO)
rm -f ch3cho.uvxsc
dat2xsc CH3CHO.dat ch3cho.uvxsc
UV_CH3CHO='ch3cho.uvxsc' #   202nm - 360 nm
if [ ! -s ${sp_dir}/ch3cho_uv_l ] || [ ! -s ${sp_dir}/ch3cho_lbl.nc ] ; then
  echo 'CH3CHO (UV)'
  rm -f ${sp_dir}/ch3cho_uv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_CH3CHO \
    -R 202 361 -i 1.0 -l 56 1.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/ch3cho_uv_l -m ${sp_dir}/ch3cho_uv_lm \
    -L ${sp_dir}/ch3cho_lbl.nc -np $procs \
     > ${sp_dir}/ch3cho_uv_log
fi

#Methylhydroperoxide (CH3OOH)
rm -f ch3ooh.uvxsc
dat2xsc CH3OOH.dat ch3ooh.uvxsc
UV_CH3OOH='ch3ooh.uvxsc' #   210nm - 405 nm
if [ ! -s ${sp_dir}/ch3ooh_uv_l ] || [ ! -s ${sp_dir}/ch3ooh_lbl.nc ] ; then
  echo 'CH3OOH (UV)'
  rm -f ${sp_dir}/ch3ooh_uv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_CH3OOH \
    -R 210 406 -i 1.0 -l 57 1.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/ch3ooh_uv_l -m ${sp_dir}/ch3ooh_uv_lm \
    -L ${sp_dir}/ch3ooh_lbl.nc -np $procs \
     > ${sp_dir}/ch3ooh_uv_log
fi

#Acetone (CH3COCH3)
UV_CH3COCH3='ch3coch3.uvxsc' #   215nm - 349 nm
ch3coch3_pt_file='pt_ch3coch3'
if [ ! -s ${sp_dir}/ch3coch3_uv_l ] || [ ! -s ${sp_dir}/ch3coch3_lbl.nc ] ; then
  echo 'CH3COCH3 (UV)'
  rm -f ${sp_dir}/ch3coch3_uv_l*
  Ccorr_k -F $ch3coch3_pt_file -UVX $UV_CH3COCH3 \
    -R 215 350 -i 1.0 -l 58 1.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -q -r $REF_PT_FILE \
    -o ${sp_dir}/ch3coch3_uv_l -m ${sp_dir}/ch3coch3_uv_lm \
    -L ${sp_dir}/ch3coch3_lbl.nc -np $procs \
     > ${sp_dir}/ch3coch3_uv_log
fi

#Methylglyoxal (CH3COCHO)
rm -f ch3cocho.uvxsc
dat2xsc CH3COCHO.dat ch3cocho.uvxsc
UV_CH3COCHO='ch3cocho.uvxsc' # 200 - 493 nm
if [ ! -s ${sp_dir}/ch3cocho_uv_l ] || [ ! -s ${sp_dir}/ch3cocho_lbl.nc ] ; then
  echo 'CH3COCHO (UV)'
  rm -f ${sp_dir}/ch3cocho_uv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_CH3COCHO \
    -R 200 494 -i 1.0 -l 59 2.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/ch3cocho_uv_l -m ${sp_dir}/ch3cocho_uv_lm \
    -L ${sp_dir}/ch3cocho_lbl.nc -np $procs \
     > ${sp_dir}/ch3cocho_uv_log
fi

#Glyoxal (CHOCHO)
rm -f chocho.uvxsc
dat2xsc CHOCHO.dat chocho.uvxsc
UV_CHOCHO='chocho.uvxsc' #   250nm - 526 nm
if [ ! -s ${sp_dir}/chocho_uv_l ] || [ ! -s ${sp_dir}/chocho_lbl.nc ] ; then
  echo 'CHOCHO (UV)'
  rm -f ${sp_dir}/chocho_uv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_CHOCHO \
    -R 250 527 -i 1.0 -l 60 1.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/chocho_uv_l -m ${sp_dir}/chocho_uv_lm \
    -L ${sp_dir}/chocho_lbl.nc -np $procs \
     > ${sp_dir}/chocho_uv_log
fi

#Glycolaldehyde (HOCH2CHO)
rm -f hoch2cho.uvxsc
dat2xsc HOCH2CHO.dat hoch2cho.uvxsc
UV_HOCH2CHO='hoch2cho.uvxsc' #   208nm - 332 nm
if [ ! -s ${sp_dir}/hoch2cho_uv_l ] || [ ! -s ${sp_dir}/hoch2cho_lbl.nc ] ; then
  echo 'HOCH2CHO (UV)'
  rm -f ${sp_dir}/hoch2cho_uv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_HOCH2CHO \
    -R 208 333 -i 1.0 -l 62 2.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/hoch2cho_uv_l -m ${sp_dir}/hoch2cho_uv_lm \
    -L ${sp_dir}/hoch2cho_lbl.nc -np $procs \
     > ${sp_dir}/hoch2cho_uv_log
fi

#Methacrolein (MACR)
#rm -f macr.uvxsc
#dat2xsc MACR.dat macr.uvxsc
#UV_MACR='macr.uvxsc' #   250nm - 395 nm
#if [ ! -s ${sp_dir}/macr_uv_l ] || [ ! -s ${sp_dir}/macr_lbl.nc ] ; then
#  echo 'MACR (UV)'
#  rm -f ${sp_dir}/macr_uv_l*
#  Ccorr_k -F $PT_SINGLE -UVX $UV_MACR \
#    -R 250 396 -i 1.0 -l 65 2.0e-3 -t 1.0e-3  \
#    -s $skelfile +S $SOLSPEC \
#    -o ${sp_dir}/macr_uv_l -m ${sp_dir}/macr_uv_lm \
#    -L ${sp_dir}/macr_lbl.nc -np $procs \
#     > ${sp_dir}/macr_uv_log
#fi

#Polyacrylonitrile (PAN)
UV_PAN='pan.uvxsc' #   196nm - 350 nm
pan_pt_file='pt_pan'
if [ ! -s ${sp_dir}/pan_uv_l ] || [ ! -s ${sp_dir}/pan_lbl.nc ] ; then
  echo 'PAN (UV)'
  rm -f ${sp_dir}/pan_uv_l*
  Ccorr_k -F $pan_pt_file -UVX $UV_PAN \
    -R 196 351 -i 1.0 -l 66 1.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -q -r $REF_PT_FILE \
    -o ${sp_dir}/pan_uv_l -m ${sp_dir}/pan_uv_lm \
    -L ${sp_dir}/pan_lbl.nc -np $procs \
     > ${sp_dir}/pan_uv_log
fi

#Methylnitrate (CH3ONO2)
rm -f ch3ono2.uvxsc
dat2xsc CH3ONO2.dat ch3ono2.uvxsc
UV_CH3ONO2='ch3ono2.uvxsc' #   192nm - 344 nm
if [ ! -s ${sp_dir}/ch3ono2_uv_l ] || [ ! -s ${sp_dir}/ch3ono2_lbl.nc ] ; then
  echo 'CH3ONO2 (UV)'
  rm -f ${sp_dir}/ch3ono2_uv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_CH3ONO2 \
    -R 192 345 -i 1.0 -l 67 2.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/ch3ono2_uv_l -m ${sp_dir}/ch3ono2_uv_lm \
    -L ${sp_dir}/ch3ono2_lbl.nc -np $procs \
     > ${sp_dir}/ch3ono2_uv_log
fi

wait

# Create the spectral file from the data calculated above
# -------------------------------------------------------
echo 'Constructing spectral file'
mv ${specfile} ${specfile}_old 2> /dev/null
mv ${specfile}_k ${specfile}_old_k 2> /dev/null
prep_spec << EOF > ${specfile}_log1 2>&1
$skelfile
n
$specfile
2
n
${SOLSPEC}
n
3
a
5
${sp_dir}/o2_xuvhr_l
5
y
${sp_dir}/o2_euvhr_l
5
y
${sp_dir}/o2_uvhr_l
5
y
${sp_dir}/o3_uvhr_l
5
y
${sp_dir}/ch4_xuv_l
5
y
${sp_dir}/ch4_euv_l
5
y
${sp_dir}/ch4_uv_l
5
y
${sp_dir}/co2_xuv_l
5
y
${sp_dir}/co2_euv_l
5
y
${sp_dir}/co2_uv_l
5
y
${sp_dir}/co_xuv_l
5
y
${sp_dir}/co_euv_l
5
y
${sp_dir}/co_uv_l
5
y
${sp_dir}/h2_xuv_l
5
y
${sp_dir}/h2_euv_l
5
y
${sp_dir}/h2_uv_l
5
y
${sp_dir}/h2o_xuv_l
5
y
${sp_dir}/h2o_euv_l
5
y
${sp_dir}/h2o_uv_l
5
y
${sp_dir}/n2_xuvhr_l
5
y
${sp_dir}/n2_euvhr_l
5
y
${sp_dir}/n2o_xuv_l
5
y
${sp_dir}/n2o_euv_l
5
y
${sp_dir}/n2o_fuv_l
5
y
${sp_dir}/n2o_uv_l
5
y
${sp_dir}/no2_xuv_l
5
y
${sp_dir}/no2_euv_l
5
y
${sp_dir}/no2_uv_l
5
y
${sp_dir}/o_xuvhr_l
5
y
${sp_dir}/o_euvhr_l
5
y
${sp_dir}/n_xuvhr_l
5
y
${sp_dir}/n_euvhr_l
5
y
${sp_dir}/h2o2_uv_l
5
y
${sp_dir}/no3_uv_l
5
y
${sp_dir}/n2o5_uv_l
5
y
${sp_dir}/ho2no2_uv_l
5
y
${sp_dir}/hno3_uv_l
5
y
${sp_dir}/ch3ooh_uv_l
5
y
${sp_dir}/hono_uv_l
5
y
${sp_dir}/ch3cho_uv_l
5
y
${sp_dir}/h2co_xuv_l
5
y
${sp_dir}/h2co_euv_l
5
y
${sp_dir}/h2co_uv_l
5
y
${sp_dir}/chocho_uv_l
5
y
${sp_dir}/ocs_uv_l
5
y
${sp_dir}/ch3ono2_uv_l
5
y
${sp_dir}/hoch2cho_uv_l
5
y
${sp_dir}/pan_uv_l
5
y
${sp_dir}/ch3cocho_uv_l
5
y
${sp_dir}/ch3coch3_uv_l
5
y
${sp_dir}/c2h2_xuv_l
5
y
${sp_dir}/c2h2_euv_l
5
y
${sp_dir}/c2h2_uv_l
5
y
${sp_dir}/hcn_euv_l
5
y
${sp_dir}/hcn_uv_l
5
y
${sp_dir}/c2h6_xuv_l
5
y
${sp_dir}/c2h6_euv_l
5
y
${sp_dir}/c2h6_uv_l
5
y
${sp_dir}/nh3_xuv_l
5
y
${sp_dir}/nh3_euv_l
5
y
${sp_dir}/nh3_uv_l
-1
EOF

# Rearrange so the major gas is listed first for each band
echo 'Determining major absorbers'
# Column ammounts integrated down to     stratopause  |  mesopause
# Column amount for Water Vapour         0.156458E-04    0.630611E-08
# Column amount for Carbon Dioxide       0.251123E-02    0.708379E-05
# Column amount for Ozone                0.784418E-05    0.128860E-07
# Column amount for Dinitrogen Oxide     0.138654E-07    0.103199E-10
# Column amount for Carbon monoxide      0.112071E-05    0.208955E-06
# Column amount for Methane              0.399384E-06    0.123864E-08
# Column amount for Oxygen               0.107215E+01    0.332647E-02
# Column amount for Nitrogen monoxide            0.356393E-05
# Column amount for Nitrogen dioxide     0.205777E-08    0.482538E-11
# Column amount for Ammonia                          0.0
# Column amount for Nitric acid                      0.0
# Column amount for Nitrogen             0.351191E+01    0.130265E-01
# Column amount for Hydrogen                         0.0
# Column amount for Carbonyl sulphide                0.0
# Column amount for Acetylene                        0.0
# Column amount for Hydrogen cyanide                 0.0
# Column amount for Atomic Oxygen        0.262064E-03    0.228072E-03
# Column amount for Atomic Nitrogen      0.299410E-09    0.260047E-09
# Column amount for Nitrate radical                  0.0
# Column amount for Dinitrogen pentoxide             0.0
# Column amount for Nitrous acid                     0.0
# Column amount for Peroxynitric acid                0.0
# Column amount for Hydrogen peroxide                0.0
# Column amount for Ethane                           0.0
# Column amount for Formaldehyde                     0.0
# Column amount for Acetaldehyde                     0.0
# Column amount for Methylhydroperoxide              0.0
# Column amount for Acetone                          0.0
# Column amount for Methylglyoxal                    0.0
# Column amount for Glyoxal                          0.0
# Column amount for Glycolaldehyde                   0.0
# Column amount for Peroxyacetyl nitrate             0.0
# Column amount for Methylnitrate                    0.0
tidy_90 <<EOF > ${specfile}_tidy_log
${specfile}
o
6
0.630611E-08
0.708379E-05
0.128860E-07
0.103199E-10
0.208955E-06
0.123864E-08
0.332647E-02
0.356393E-05
0.482538E-11
0.0
0.0
0.130265E-01
0.0
0.0
0.0
0.0
0.228072E-03
0.260047E-09
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
-1
EOF

# Define sub-bands and photolysis reactions
echo 'Adding photolysis reactions'
prep_spec << EOF > ${specfile}_log2 2>&1
${specfile}
a
17
-1
${SOLSPEC}
a
0
0
0
20
7
1
n
O2_1.qy
O2_1.pe
20
y
7
2
n
O2_2.qy
O2_2.pe
20
y
7
6
n
O2_6.qy
O2_6.pe
20
y
7
7
n
O2_7.qy
O2_7.pe
20
y
13
1
n
N2_1.qy
N2_1.pe
20
y
13
2
n
N2_2.qy
N2_2.pe
20
y
13
3
n
N2_3.qy
N2_3.pe
20
y
39
1
n
O_1.qy
O_1.pe
20
y
39
2
n
O_2.qy
O_2.pe
20
y
39
3
n
O_3.qy
O_3.pe
20
y
39
4
n
O_4.qy
O_4.pe
20
y
39
5
n
O_5.qy
O_5.pe
20
y
40
1
n
N_1.qy
N_1.pe
20
y
1
2
n
${hj}/H2O_2.qy

20
y
1
3
n
${hj}/H2O_3.qy

20
y
1
5
n
${hj}/H2O_5.qy

20
y
3
1
y
O3_Matsumi2002_1.qy

20
y
3
4
y
O3_Matsumi2002_4.qy

20
y
10
1
y
NO2_jpl_1.qy

20
y
45
1
y
H2O2_1.qy

20
y
42
1
y
N2O5_1.qy

20
y
41
1
y
NO3_1.qy

20
y
44
2
y
HO2NO2_jpl_2.qy

20
y
41
2
y
NO3_2.qy


20
y
12
1
y
HNO3_1.qy

20
y
57
1
y
CH3OOH_1.qy

20
y
43
1
y
HONO_1.qy

20
y
56
1
y
CH3CHO_1.qy

20
y
48
1
y
H2CO_1.qy

20
y
48
2
y
H2CO_2.qy

20
y
60
1
y
CHOCHO_1.qy

20
y
60
2
y
CHOCHO_2.qy

20
y
25
1
y
OCS_1.qy

20
y
67
1
y
CH3ONO2_1.qy

20
y
62
1
y
HOCH2CHO_1.qy

20
y
66
1
y
PAN_1.qy

20
y
66
2
y
PAN_2.qy

20
y
4
1
y
N2O_1.qy

20
y
59
1
y
CH3COCHO_1.qy

20
y
58
1
y
CH3COCH3_1.qy

20
y
2
1
y
${hj}/CO2_1.qy

20
y
2
2
y
${hj}/CO2_2.qy

20
y
34
1
y
${hj}/C2H2_1.qy

20
y
6
1
y
${hj}/CH4_1.qy

20
y
6
2
y
${hj}/CH4_2.qy

20
y
6
3
y
${hj}/CH4_3.qy

20
y
6
4
y
${hj}/CH4_4.qy

20
y
35
1
y
${hj}/HCN_1.qy

20
y
46
1
y
${hj}/C2H6_1.qy

20
y
46
2
y
${hj}/C2H6_2.qy

20
y
46
3
y
${hj}/C2H6_3.qy

20
y
46
4
y
${hj}/C2H6_4.qy

20
y
46
5
y
${hj}/C2H6_5.qy

20
y
11
1
y
${hj}/NH3_1.qy

-1
EOF

echo -n 'Finished mk_sp_2000_earth: '; date
exit 0
