#!/bin/bash

echo -n 'Started mk_sp_2000_earth: '; date

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

# Set environment variables
# -------------------------
procs=4
procs_s=8
. ./env_earth

sp_dir="/data/users/james.manners/jm_earth_hr"
mkdir -p ${sp_dir}

hj="exo_species"


# Create skeleton spectral file
# -----------------------------
specfile=${sp_dir}/sp_2000_earth
skelfile=${sp_dir}/sp_2000_earth_skel
./mk_sp_2000_earth_skel $skelfile > /dev/null


# Gas absorption coefficients:
# ----------------------------
# Water vapour (H2O)
# ----------------------------
rm -f h2o.uvxsc
dat2xsc --eric ericH2O.dat h2o.uvxsc
UV_H2O='h2o.uvxsc' #   6 - 216 nm
if [ ! -s ${sp_dir}/h2o_xuv_l ] || [ ! -s ${sp_dir}/h2o_lbl_xuv.nc ] ; then
  echo 'H2O: XUV - continuum'
  rm -f ${sp_dir}/h2o_xuv_l*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $UV_H2O \
    -R 6 10 -i 1000.0 -l 1 1.0e-5 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/h2o_xuv_l -m ${sp_dir}/h2o_xuv_lm \
    -L ${sp_dir}/h2o_lbl_xuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/h2o_xuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/h2o_xuv_log
  fi
fi
if [ ! -s ${sp_dir}/h2o_euv_l ] || [ ! -s ${sp_dir}/h2o_lbl_euv.nc ] ; then
  echo 'H2O: extreme UV - continuum'
  rm -f ${sp_dir}/h2o_euv_l*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $UV_H2O \
    -R 11 100 -i 10.0 -l 1 1.0e-5 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/h2o_euv_l -m ${sp_dir}/h2o_euv_lm \
    -L ${sp_dir}/h2o_lbl_euv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/h2o_euv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/h2o_euv_log
  fi
fi
if [ ! -s ${sp_dir}/h2o_fuv_l ] || [ ! -s ${sp_dir}/h2o_lbl_fuv.nc ] ; then
  echo 'H2O: far UV - continuum'
  rm -f ${sp_dir}/h2o_fuv_l*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $UV_H2O \
    -R 101 217 -i 1.0 -l 1 1.0e-5 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/h2o_fuv_l -m ${sp_dir}/h2o_fuv_lm \
    -L ${sp_dir}/h2o_lbl_fuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/h2o_fuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/h2o_fuv_log
  fi
fi
rm -f h2o.uvxsc

if [ ! -s $sp_dir/h2o_nuv_l ] ; then
  if [ ! -s $H2O_LBL_VIS ] ; then
    echo "H2O: No visible LBL file: please run ./mk_h2o_lbl_2000_earth"
    exit 1
  else
    echo "H2O: near UV - lines"
    rm -f $sp_dir/h2o_nuv_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 238 320 -l 1 ${COL_MASS_K_H2O} -b 5.0e-4 \
      -s $skelfile +S $SOLSPEC -lk \
      -o $sp_dir/h2o_nuv_l -m $sp_dir/h2o_nuv_lm \
      -L $H2O_LBL_VIS -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/h2o_nuv_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/h2o_nuv_log
    fi
  fi
fi
if [ ! -s $sp_dir/h2o_vis_l ] ; then
  if [ ! -s $H2O_LBL_VIS ] ; then
    echo "H2O: No visible LBL file: please run ./mk_h2o_lbl_2000_earth"
    exit 1
  else
    echo "H2O: visible"
    rm -f $sp_dir/h2o_vis_l*
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 321 500 -l 1 ${COL_MASS_K_H2O} -b 5.0e-4 \
      -s $skelfile +S $SOLSPEC -lk \
      -o $sp_dir/h2o_vis_l -m $sp_dir/h2o_vis_lm \
      -L $H2O_LBL_VIS -np $procs"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/h2o_vis_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/h2o_vis_log &
    fi
  fi
fi
if [ ! -s $sp_dir/h2o_nirf_l ] ; then
  if [ ! -s $H2O_LBL_IRF ] ; then
    echo "H2O: No infra-red LBL file: please run ./mk_h2o_lbl_2000_earth"
    exit 1
  else
    echo "H2O: near infra-red"
    rm -f $sp_dir/h2o_nirf_l*
    rm -f $sp_dir/h2o_nirf_l_map.nc
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 501 1000 -l 1 ${COL_MASS_K_H2O} -b 5.0e-4 \
      -s $skelfile +S $SOLSPEC -lk \
      -o $sp_dir/h2o_nirf_l -m $sp_dir/h2o_nirf_lm \
      -L $H2O_LBL_IRF -np $procs \
      -sm $sp_dir/h2o_nirf_l_map.nc"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/h2o_nirf_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/h2o_nirf_log
    fi
  fi
fi
if [ ! -s $sp_dir/h2o_mirf_l ] ; then
  if [ ! -s $H2O_LBL_IRF ] ; then
    echo "H2O: No infra-red LBL file: please run ./mk_h2o_lbl_2000_earth"
    exit 1
  else
    echo "H2O: mid infra-red"
    rm -f $sp_dir/h2o_mirf_l*
    rm -f $sp_dir/h2o_mirf_l_map.nc
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1001 1500 -l 1 ${COL_MASS_K_H2O} -b 5.0e-4 \
      -s $skelfile -u -lk \
      -o $sp_dir/h2o_mirf_l -m $sp_dir/h2o_mirf_lm \
      -L $H2O_LBL_IRF -np $procs \
      -sm $sp_dir/h2o_mirf_l_map.nc"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/h2o_mirf_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/h2o_mirf_log
    fi
  fi
fi
if [ ! -s $sp_dir/h2o_firf_l ] ; then
  if [ ! -s $H2O_LBL_IRF ] ; then
    echo "H2O: No infra-red LBL file: please run ./mk_h2o_lbl_2000_earth"
    exit 1
  else
    echo "H2O: far infra-red"
    rm -f $sp_dir/h2o_firf_l*
    rm -f $sp_dir/h2o_firf_l_map.nc
    ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1501 2000 -l 1 ${COL_MASS_K_H2O} -b 5.0e-4 \
      -s $skelfile -u -lk \
      -o $sp_dir/h2o_firf_l -m $sp_dir/h2o_firf_lm \
      -L $H2O_LBL_IRF -np $procs \
      -sm $sp_dir/h2o_firf_l_map.nc"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs -o $sp_dir/h2o_firf_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/h2o_firf_log
    fi
  fi
fi
if [ ! -s $sp_dir/h2o_nir_s ] ; then
  if [ ! -s $H2O_LBL_IRF ] ; then
    echo "H2O: No infra-red LBL file: please run ./mk_h2o_lbl_2000_earth"
    exit 1
  else
    echo "H2O: near-ir self-broadened continuum"
    rm -f $sp_dir/h2o_nir_s*
	  ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 501 1000 -C 33 1.0e-4 1.0e4 -P 7 \
      -e ${CONT_H2O_S260} ${CONT_H2O_S260} \
      -s $skelfile -u -p -r ${REF_PT_FILE} \
      -o $sp_dir/h2o_nir_s -m $sp_dir/h2o_nir_sm \
      -L $H2O_LBL_IRF -np $procs_s"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs_s -o $sp_dir/h2o_nir_s_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/h2o_nir_s_log
    fi
  fi
fi
if [ ! -s $sp_dir/h2o_mir_s ] ; then
  if [ ! -s $H2O_LBL_IRF ] ; then
    echo "H2O: No infra-red LBL file: please run ./mk_h2o_lbl_2000_earth"
    exit 1
  else
    echo "H2O: mid-ir self-broadened continuum"
    rm -f $sp_dir/h2o_mir_s*
	  ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1001 1500 -C 33 1.0e-4 1.0e4 -P 7 \
      -e ${CONT_H2O_S260} ${CONT_H2O_S260} \
      -s $skelfile -u -p -r ${REF_PT_FILE} \
      -o $sp_dir/h2o_mir_s -m $sp_dir/h2o_mir_sm \
      -L $H2O_LBL_IRF -np $procs_s"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs_s -o $sp_dir/h2o_mir_s_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/h2o_mir_s_log
    fi
  fi
fi
if [ ! -s $sp_dir/h2o_fir_s ] ; then
  if [ ! -s $H2O_LBL_IRF ] ; then
    echo "H2O: No infra-red LBL file: please run ./mk_h2o_lbl_2000_earth"
    exit 1
  else
    echo "H2O: far-ir self-broadened continuum"
    rm -f $sp_dir/h2o_fir_s*
	  ck_args="Ccorr_k -F ${GAS_DATA_DIR}/${PT_FILE} \
      -R 1001 1500 -C 33 1.0e-4 1.0e4 -P 7 \
      -e ${CONT_H2O_S260} ${CONT_H2O_S260} \
      -s $skelfile -u -p -r ${REF_PT_FILE} \
      -o $sp_dir/h2o_fir_s -m $sp_dir/h2o_fir_sm \
      -L $H2O_LBL_IRF -np $procs_s"
    if command -v sbatch &> /dev/null ; then
      sbatch -W -n $procs_s -o $sp_dir/h2o_fir_s_log -t 360 ${ck_args} &
    else
      ${ck_args} > $sp_dir/h2o_fir_s_log
    fi
  fi
fi


# ----------------------------
# Carbon Dioxide (CO2)
# ----------------------------
rm -f co2_hb2010.uvxsc
dat2xsc CO2_HB2010_300K.dat co2_hb2010.uvxsc
UV_CO2='co2_hb2010.uvxsc' #   0.1254-201.6nm
if [ ! -s ${sp_dir}/co2_xuv_l ] || [ ! -s ${sp_dir}/co2_lbl_xuv.nc ] ; then
  echo 'CO2: XUV - continuum'
  rm -f ${sp_dir}/co2_xuv_l*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $UV_CO2 \
    -R 1 10 -i 1000.0 -l 2 1.0e1 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/co2_xuv_l -m ${sp_dir}/co2_xuv_lm \
    -L ${sp_dir}/co2_lbl_xuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/co2_xuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/co2_xuv_log
  fi
fi
if [ ! -s ${sp_dir}/co2_euv_l ] || [ ! -s ${sp_dir}/co2_lbl_euv.nc ] ; then
  echo 'CO2: extreme UV - continuum'
  rm -f ${sp_dir}/co2_euv_l*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $UV_CO2 \
    -R 11 100 -i 10.0 -l 2 1.0e1 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/co2_euv_l -m ${sp_dir}/co2_euv_lm \
    -L ${sp_dir}/co2_lbl_euv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/co2_euv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/co2_euv_log
  fi
fi
if [ ! -s ${sp_dir}/co2_fuv_l ] || [ ! -s ${sp_dir}/co2_lbl_fuv.nc ] ; then
  echo 'CO2: far UV - continuum'
  rm -f ${sp_dir}/co2_fuv_l*
  ck_args="Ccorr_k -F $PT_SINGLE -UVX $UV_CO2 \
    -R 101 202 -i 1.0 -l 2 1.0e1 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/co2_fuv_l -m ${sp_dir}/co2_fuv_lm \
    -L ${sp_dir}/co2_lbl_fuv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/co2_fuv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/co2_fuv_log
  fi
fi
rm -f co2_hb2010.uvxsc


# ----------------------------
# Ozone (O3)
# ----------------------------
UV_O3="$RAD_DATA/gases/O3_110nm-1100nm.xsc"
o3_pt_file="$RAD_DATA/gases/pt_o3_uv"
if [ ! -s ${sp_dir}/o3_uv_l ] || [ ! -s ${sp_dir}/o3_lbl_uv.nc ] ; then
  echo 'O3 (far-UV - near-IR continuum)'
  rm -f ${sp_dir}/o3_uv_l*
  ck_args="Ccorr_k -F $o3_pt_file -X $UV_O3 \
    -R 111 1091 -i 1.0 -l 3 1.0e-2 -t 1.0e-3 \
    -s $skelfile +S $SOLSPEC -lk \
    -o ${sp_dir}/o3_uv_l -m ${sp_dir}/o3_uv_lm \
    -L ${sp_dir}/o3_lbl_uv.nc -np $procs"
  if command -v sbatch &> /dev/null ; then
    sbatch -W -n $procs -o ${sp_dir}/o3_uv_log -t 60 ${ck_args} &
  else
    ${ck_args} > ${sp_dir}/o3_uv_log
  fi
fi

##### got to here
exit 0

# Dinitrogen Oxide (N2O)
rm -f n2o_???K.uvxsc n2o_298K_ext.uvxsc n2o_208-298K.uvxsc
rm -f n2o_???K.dat
calc_n2o_xsc
cat n2o_298K_6-160nm.dat n2o_298K.dat > n2o_298K_ext.dat
dat2xsc -t 208 n2o_208K.dat n2o_208K.uvxsc
dat2xsc -t 238 n2o_238K.dat n2o_238K.uvxsc
dat2xsc -t 268 n2o_268K.dat n2o_268K.uvxsc
dat2xsc -t 298 n2o_298K_ext.dat n2o_298K_ext.uvxsc
cat n2o_208K.uvxsc n2o_238K.uvxsc n2o_268K.uvxsc n2o_298K_ext.uvxsc \
		> n2o_208-298K.uvxsc
UV_N2O='n2o_208-298K.uvxsc' #   6 - 250 nm
n2o_pt_file="pt_n2o"
if [ ! -s ${sp_dir}/n2o_xuv_l ] || [ ! -s $SW_DATA/n2o_lbl_xuv.nc ] ; then
  echo 'N2O (XUV continuum)'
  rm -f ${sp_dir}/n2o_xuv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_N2O \
    -R 7 10 -i 1000.0 -l 4 5.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/n2o_xuv_l -m ${sp_dir}/n2o_xuv_lm \
    -L $SW_DATA/n2o_lbl_xuv.nc -np $procs \
     > ${sp_dir}/n2o_xuv_log
fi
if [ ! -s ${sp_dir}/n2o_euv_l ] || [ ! -s $SW_DATA/n2o_lbl_euv.nc ] ; then
  echo 'N2O (EUV continuum)'
  rm -f ${sp_dir}/n2o_euv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_N2O \
    -R 11 100 -i 10.0 -l 4 5.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/n2o_euv_l -m ${sp_dir}/n2o_euv_lm \
    -L $SW_DATA/n2o_lbl_euv.nc -np $procs \
     > ${sp_dir}/n2o_euv_log
fi
if [ ! -s ${sp_dir}/n2o_fuv_l ] || [ ! -s $SW_DATA/n2o_lbl_fuv.nc ] ; then
  echo 'N2O (FUV continuum)'
  rm -f ${sp_dir}/n2o_fuv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_N2O \
    -R 101 160 -i 1.0 -l 4 5.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/n2o_fuv_l -m ${sp_dir}/n2o_fuv_lm \
    -L $SW_DATA/n2o_lbl_fuv.nc -np $procs \
     > ${sp_dir}/n2o_fuv_log
fi
if [ ! -s ${sp_dir}/n2o_uv_l ] || [ ! -s $SW_DATA/n2o_lbl_uv.nc ] ; then
  echo 'N2O (UV continuum)'
  rm -f ${sp_dir}/n2o_uv_l*
  Ccorr_k -F $n2o_pt_file -UVX $UV_N2O \
    -R 161 250 -i 1.0 -l 4 5.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -q -r $REF_PT_FILE \
    -o ${sp_dir}/n2o_uv_l -m ${sp_dir}/n2o_uv_lm \
    -L $SW_DATA/n2o_lbl_uv.nc -np $procs \
     > ${sp_dir}/n2o_uv_log
fi

# Carbon Monoxide (CO)
rm -f co.uvxsc
dat2xsc CO.dat co.uvxsc
UV_CO='co.uvxsc'   #   7 - 163 nm
if [ ! -s ${sp_dir}/co_xuv_l ] || [ ! -s $SW_DATA/co_lbl_xuv.nc ] ; then
  echo 'CO (XUV continuum)'
  rm -f ${sp_dir}/co_xuv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_CO \
    -R 7 10 -i 1000.0 -l 5 2.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/co_xuv_l -m ${sp_dir}/co_xuv_lm \
    -L $SW_DATA/co_lbl_xuv.nc -np $procs \
     > ${sp_dir}/co_xuv_log
fi
if [ ! -s ${sp_dir}/co_euv_l ] || [ ! -s $SW_DATA/co_lbl_euv.nc ] ; then
  echo 'CO (EUV continuum)'
  rm -f ${sp_dir}/co_euv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_CO \
    -R 11 100 -i 10.0 -l 5 2.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/co_euv_l -m ${sp_dir}/co_euv_lm \
    -L $SW_DATA/co_lbl_euv.nc -np $procs \
     > ${sp_dir}/co_euv_log
fi
if [ ! -s ${sp_dir}/co_uv_l ] || [ ! -s $SW_DATA/co_lbl_uv.nc ] ; then
  echo 'CO (UV continuum)'
  rm -f ${sp_dir}/co_uv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_CO \
    -R 101 164 -i 1.0 -l 5 2.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/co_uv_l -m ${sp_dir}/co_uv_lm \
    -L $SW_DATA/co_lbl_uv.nc -np $procs \
     > ${sp_dir}/co_uv_log
fi

# Methane (CH4)
rm -f ch4.uvxsc
dat2xsc CH4.dat ch4.uvxsc
UV_CH4='ch4.uvxsc' #   6 - 151 nm
if [ ! -s ${sp_dir}/ch4_xuv_l ] || [ ! -s $SW_DATA/ch4_lbl_xuv.nc ] ; then
  echo 'CH4 (XUV continuum)'
  rm -f ${sp_dir}/ch4_xuv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_CH4 \
    -R 6 10 -i 1000.0 -l 6 1.0e-2 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/ch4_xuv_l -m ${sp_dir}/ch4_xuv_lm \
    -L $SW_DATA/ch4_lbl_xuv.nc -np $procs \
     > ${sp_dir}/ch4_xuv_log
fi
if [ ! -s ${sp_dir}/ch4_euv_l ] || [ ! -s $SW_DATA/ch4_lbl_euv.nc ] ; then
  echo 'CH4 (EUV continuum)'
  rm -f ${sp_dir}/ch4_euv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_CH4 \
    -R 11 100 -i 10.0 -l 6 1.0e-2 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/ch4_euv_l -m ${sp_dir}/ch4_euv_lm \
    -L $SW_DATA/ch4_lbl_euv.nc -np $procs \
     > ${sp_dir}/ch4_euv_log
fi
if [ ! -s ${sp_dir}/ch4_uv_l ] || [ ! -s $SW_DATA/ch4_lbl_uv.nc ] ; then
  echo 'CH4 (UV continuum)'
  rm -f ${sp_dir}/ch4_uv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_CH4 \
    -R 101 152 -i 1.0 -l 6 1.0e-2 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/ch4_uv_l -m ${sp_dir}/ch4_uv_lm \
    -L $SW_DATA/ch4_lbl_uv.nc -np $procs \
     > ${sp_dir}/ch4_uv_log
fi

# Oxygen (O2)
rm -f o2_hires.uvxsc
dat2xsc O2.dat o2_hires.uvxsc
UV_O2_HIRES='o2_hires.uvxsc' # 0.04 - 294 nm
if [ ! -s ${sp_dir}/o2_xuvhr_l ] || [ ! -s $SW_DATA/o2_lbl_xuvhr.nc ] ; then
  echo 'O2 (XUV continuum)'
  rm -f ${sp_dir}/o2_xuvhr_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_O2_HIRES \
    -R 1 10 -i 1000.0 -l 7 2.3e3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/o2_xuvhr_l -m ${sp_dir}/o2_xuvhr_lm \
    -L $SW_DATA/o2_lbl_xuvhr.nc -np $procs \
     > ${sp_dir}/o2_xuvhr_log
fi
if [ ! -s ${sp_dir}/o2_euvhr_l ] || [ ! -s $SW_DATA/o2_lbl_euvhr.nc ] ; then
  echo 'O2 (EUV continuum)'
  rm -f ${sp_dir}/o2_euvhr_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_O2_HIRES \
    -R 11 100 -i 10.0 -l 7 2.3e3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/o2_euvhr_l -m ${sp_dir}/o2_euvhr_lm \
    -L $SW_DATA/o2_lbl_euvhr.nc -np $procs \
     > ${sp_dir}/o2_euvhr_log
fi
if [ ! -s ${sp_dir}/o2_uvhr_l ] || [ ! -s $SW_DATA/o2_lbl_uvhr.nc ] ; then
  echo 'O2 (UV continuum)'
  rm -f ${sp_dir}/o2_uvhr_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_O2_HIRES \
    -R 101 294 -i 1.0 -l 7 2.3e3 -t 5.0e-4  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/o2_uvhr_l -m ${sp_dir}/o2_uvhr_lm \
    -L $SW_DATA/o2_lbl_uvhr.nc -np $procs \
     > ${sp_dir}/o2_uvhr_log
fi

#Nitrogen Dioxide (NO2)
UV_NO2='no2_cat.uvxsc' #   205 - 495nm
no2_pt_file='pt_no2'
if [ ! -s ${sp_dir}/no2_xuv_l ] || [ ! -s $SW_DATA/no2_lbl_xuv.nc ] ; then
  echo 'NO2 (XUV continuum)'
  rm -f ${sp_dir}/no2_xuv_l*
  Ccorr_k -F $no2_pt_file -UVX $UV_NO2 \
    -R 7 10 -i 1000.0 -l 10 5.0e-4 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -q -r $REF_PT_FILE \
    -o ${sp_dir}/no2_xuv_l -m ${sp_dir}/no2_xuv_lm \
    -L $SW_DATA/no2_lbl_xuv.nc -np $procs \
     > ${sp_dir}/no2_xuv_log
fi
if [ ! -s ${sp_dir}/no2_euv_l ] || [ ! -s $SW_DATA/no2_lbl_euv.nc ] ; then
  echo 'NO2 (EUV continuum)'
  rm -f ${sp_dir}/no2_euv_l*
  Ccorr_k -F $no2_pt_file -UVX $UV_NO2 \
    -R 11 100 -i 10.0 -l 10 5.0e-4 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -q -r $REF_PT_FILE \
    -o ${sp_dir}/no2_euv_l -m ${sp_dir}/no2_euv_lm \
    -L $SW_DATA/no2_lbl_euv.nc -np $procs \
     > ${sp_dir}/no2_euv_log
fi
if [ ! -s ${sp_dir}/no2_uv_l ] || [ ! -s $SW_DATA/no2_lbl_uv.nc ] ; then
  echo 'NO2 (UV continuum)'
  rm -f ${sp_dir}/no2_uv_l*
  Ccorr_k -F $no2_pt_file -UVX $UV_NO2 \
    -R 101 724 -i 1.0 -l 10 5.0e-4 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -q -r $REF_PT_FILE \
    -o ${sp_dir}/no2_uv_l -m ${sp_dir}/no2_uv_lm \
    -L $SW_DATA/no2_lbl_uv.nc -np $procs \
     > ${sp_dir}/no2_uv_log
fi

#Ammonia (NH3)
UV_NH3="${hj}/nh3.uvxsc"  #   7nm - 229 nm
if [ ! -s ${sp_dir}/nh3_xuv_l ] || [ ! -s $SW_DATA/nh3_lbl_xuv.nc ] ; then
  echo 'NH3 (XUV)'
  rm -f ${sp_dir}/nh3_xuv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_NH3 \
    -R 7 10 -i 1000.0 -l 11 1.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/nh3_xuv_l -m ${sp_dir}/nh3_xuv_lm \
    -L $SW_DATA/nh3_lbl_xuv.nc -np $procs \
     > ${sp_dir}/nh3_xuv_log
fi
if [ ! -s ${sp_dir}/nh3_euv_l ] || [ ! -s $SW_DATA/nh3_lbl_euv.nc ] ; then
  echo 'NH3 (EUV)'
  rm -f ${sp_dir}/nh3_euv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_NH3 \
    -R 11 100 -i 10.0 -l 11 1.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/nh3_euv_l -m ${sp_dir}/nh3_euv_lm \
    -L $SW_DATA/nh3_lbl_euv.nc -np $procs \
     > ${sp_dir}/nh3_euv_log
fi
if [ ! -s ${sp_dir}/nh3_uv_l ] || [ ! -s $SW_DATA/nh3_lbl_uv.nc ] ; then
  echo 'NH3 (UV)'
  rm -f ${sp_dir}/nh3_uv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_NH3 \
    -R 101 230 -i 1.0 -l 11 1.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/nh3_uv_l -m ${sp_dir}/nh3_uv_lm \
    -L $SW_DATA/nh3_lbl_uv.nc -np $procs \
     > ${sp_dir}/nh3_uv_log
fi

#Nitric Acid (HNO3)
#rm -f hno3.uvxsc
#dat2xsc HNO3.dat hno3.uvxsc
UV_HNO3='hno3_cat.uvxsc' #   105nm - 350 nm
hno3_pt_file='pt_hno3'
if [ ! -s ${sp_dir}/hno3_uv_l ] || [ ! -s $SW_DATA/hno3_lbl.nc ] ; then
  echo 'HNO3 (UV)'
  rm -f ${sp_dir}/hno3_uv_l*
  Ccorr_k -F $hno3_pt_file -UVX $UV_HNO3 \
    -R 105 350 -i 1.0 -l 12 2.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -q -r $REF_PT_FILE \
    -o ${sp_dir}/hno3_uv_l -m ${sp_dir}/hno3_uv_lm \
    -L $SW_DATA/hno3_lbl.nc -np $procs \
     > ${sp_dir}/hno3_uv_log
fi

# Nitrogen (N2)
rm -f n2_hires.uvxsc
dat2xsc N2.dat n2_hires.uvxsc
UV_N2_HIRES='n2_hires.uvxsc' # 0.04 - 102.7 nm
if [ ! -s ${sp_dir}/n2_xuvhr_l ] || [ ! -s $SW_DATA/n2_lbl_xuvhr.nc ] ; then
  echo 'N2 (XUV continuum)'
  rm -f ${sp_dir}/n2_xuvhr_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_N2_HIRES \
    -R 1 10 -i 1000.0 -l 13 7.5e3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/n2_xuvhr_l -m ${sp_dir}/n2_xuvhr_lm \
    -L $SW_DATA/n2_lbl_xuvhr.nc -np $procs \
     > ${sp_dir}/n2_xuvhr_log
fi
if [ ! -s ${sp_dir}/n2_euvhr_l ] || [ ! -s $SW_DATA/n2_lbl_euvhr.nc ] ; then
  echo 'N2 (EUV continuum)'
  rm -f ${sp_dir}/n2_euvhr_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_N2_HIRES \
    -R 11 100 -i 10.0 -l 13 7.5e3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/n2_euvhr_l -m ${sp_dir}/n2_euvhr_lm \
    -L $SW_DATA/n2_lbl_euvhr.nc -np $procs \
     > ${sp_dir}/n2_euvhr_log
fi

# Hydrogen (H2)
rm -f h2.uvxsc
dat2xsc H2.dat h2.uvxsc
UV_H2='h2.uvxsc'   #   5 - 116 nm
if [ ! -s ${sp_dir}/h2_xuv_l ] || [ ! -s $SW_DATA/h2_lbl_xuv.nc ] ; then
  echo 'H2 (XUV continuum)'
  rm -f ${sp_dir}/h2_xuv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_H2 \
    -R 5 10 -i 1000.0 -l 23 5.0e-4 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/h2_xuv_l -m ${sp_dir}/h2_xuv_lm \
    -L $SW_DATA/h2_lbl_xuv.nc -np $procs \
     > ${sp_dir}/h2_xuv_log
fi
if [ ! -s ${sp_dir}/h2_euv_l ] || [ ! -s $SW_DATA/h2_lbl_euv.nc ] ; then
  echo 'H2 (EUV continuum)'
  rm -f ${sp_dir}/h2_euv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_H2 \
    -R 11 100 -i 10.0 -l 23 5.0e-4 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/h2_euv_l -m ${sp_dir}/h2_euv_lm \
    -L $SW_DATA/h2_lbl_euv.nc -np $procs \
     > ${sp_dir}/h2_euv_log
fi
if [ ! -s ${sp_dir}/h2_uv_l ] || [ ! -s $SW_DATA/h2_lbl_uv.nc ] ; then
  echo 'H2 (UV continuum)'
  rm -f ${sp_dir}/h2_uv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_H2 \
    -R 101 117 -i 1.0 -l 23 5.0e-4 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/h2_uv_l -m ${sp_dir}/h2_uv_lm \
    -L $SW_DATA/h2_lbl_uv.nc -np $procs \
     > ${sp_dir}/h2_uv_log
fi

#Carbonyl Sulphide (OCS)
UV_OCS='ocs.uvxsc' #   186nm - 292 nm
ocs_pt_file='pt_ocs'
if [ ! -s ${sp_dir}/ocs_uv_l ] || [ ! -s $SW_DATA/ocs_lbl.nc ] ; then
  echo 'OCS (UV)'
  rm -f ${sp_dir}/ocs_uv_l*
  Ccorr_k -F $ocs_pt_file -UVX $UV_OCS \
    -R 186 293 -i 1.0 -l 25 2.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -q -r $REF_PT_FILE \
    -o ${sp_dir}/ocs_uv_l -m ${sp_dir}/ocs_uv_lm \
    -L $SW_DATA/ocs_lbl.nc -np $procs \
     > ${sp_dir}/ocs_uv_log
fi

#Acetylene (C2H2)
UV_C2H2="${hj}/c2h2.uvxsc"  #   7nm - 228 nm
if [ ! -s ${sp_dir}/c2h2_xuv_l ] || [ ! -s $SW_DATA/c2h2_lbl_xuv.nc ] ; then
  echo 'C2H2 (XUV)'
  rm -f ${sp_dir}/c2h2_xuv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_C2H2 \
    -R 7 10 -i 1000.0 -l 34 1.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/c2h2_xuv_l -m ${sp_dir}/c2h2_xuv_lm \
    -L $SW_DATA/c2h2_lbl_xuv.nc -np $procs \
     > ${sp_dir}/c2h2_xuv_log
fi
if [ ! -s ${sp_dir}/c2h2_euv_l ] || [ ! -s $SW_DATA/c2h2_lbl_euv.nc ] ; then
  echo 'C2H2 (EUV)'
  rm -f ${sp_dir}/c2h2_euv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_C2H2 \
    -R 11 100 -i 10.0 -l 34 1.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/c2h2_euv_l -m ${sp_dir}/c2h2_euv_lm \
    -L $SW_DATA/c2h2_lbl_euv.nc -np $procs \
     > ${sp_dir}/c2h2_euv_log
fi
if [ ! -s ${sp_dir}/c2h2_uv_l ] || [ ! -s $SW_DATA/c2h2_lbl_uv.nc ] ; then
  echo 'C2H2 (UV)'
  rm -f ${sp_dir}/c2h2_uv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_C2H2 \
    -R 101 229 -i 1.0 -l 34 1.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/c2h2_uv_l -m ${sp_dir}/c2h2_uv_lm \
    -L $SW_DATA/c2h2_lbl_uv.nc -np $procs \
     > ${sp_dir}/c2h2_uv_log
fi

#Hydrogen Cynanide (HCN)
UV_HCN="${hj}/hcn.uvxsc"  #   80nm - 184 nm
if [ ! -s ${sp_dir}/hcn_euv_l ] || [ ! -s $SW_DATA/hcn_lbl_euv.nc ] ; then
  echo 'HCN (EUV)'
  rm -f ${sp_dir}/hcn_euv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_HCN \
    -R 84 100 -i 10.0 -l 35 1.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/hcn_euv_l -m ${sp_dir}/hcn_euv_lm \
    -L $SW_DATA/hcn_lbl_euv.nc -np $procs \
     > ${sp_dir}/hcn_euv_log
fi
if [ ! -s ${sp_dir}/hcn_uv_l ] || [ ! -s $SW_DATA/hcn_lbl_uv.nc ] ; then
  echo 'HCN (UV)'
  rm -f ${sp_dir}/hcn_uv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_HCN \
    -R 101 185 -i 1.0 -l 35 1.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/hcn_uv_l -m ${sp_dir}/hcn_uv_lm \
    -L $SW_DATA/hcn_lbl_uv.nc -np $procs \
     > ${sp_dir}/hcn_uv_log
fi

# Atomic Oxygen (O)
rm -f o.uvxsc
dat2xsc O.dat o.uvxsc
UV_O='o.uvxsc' # 0.04 - 102.7 nm
if [ ! -s ${sp_dir}/o_xuvhr_l ] || [ ! -s $SW_DATA/o_lbl_xuvhr.nc ] ; then
  echo 'O (XUV continuum)'
  rm -f ${sp_dir}/o_xuvhr_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_O \
    -R 1 10 -i 1000.0 -l 39 2.6e-4 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/o_xuvhr_l -m ${sp_dir}/o_xuvhr_lm \
    -L $SW_DATA/o_lbl_xuvhr.nc -np $procs \
     > ${sp_dir}/o_xuvhr_log
fi
if [ ! -s ${sp_dir}/o_euvhr_l ] || [ ! -s $SW_DATA/o_lbl_euvhr.nc ] ; then
  echo 'O (EUV continuum)'
  rm -f ${sp_dir}/o_euvhr_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_O \
    -R 11 93 -i 10.0 -l 39 2.6e-4 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/o_euvhr_l -m ${sp_dir}/o_euvhr_lm \
    -L $SW_DATA/o_lbl_euvhr.nc -np $procs \
     > ${sp_dir}/o_euvhr_log
fi

# Atomic Nitrogen (N)
rm -f n.uvxsc
dat2xsc N.dat n.uvxsc
UV_N='n.uvxsc' # 0.04 - 102.7 nm
if [ ! -s ${sp_dir}/n_xuvhr_l ] || [ ! -s $SW_DATA/n_lbl_xuvhr.nc ] ; then
  echo 'N (XUV continuum)'
  rm -f ${sp_dir}/n_xuvhr_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_N \
    -R 1 10 -i 1000.0 -l 40 3.0e-10 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/n_xuvhr_l -m ${sp_dir}/n_xuvhr_lm \
    -L $SW_DATA/n_lbl_xuvhr.nc -np $procs \
     > ${sp_dir}/n_xuvhr_log
fi
if [ ! -s ${sp_dir}/n_euvhr_l ] || [ ! -s $SW_DATA/n_lbl_euvhr.nc ] ; then
  echo 'N (EUV continuum)'
  rm -f ${sp_dir}/n_euvhr_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_N \
    -R 11 88 -i 10.0 -l 40 3.0e-10 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/n_euvhr_l -m ${sp_dir}/n_euvhr_lm \
    -L $SW_DATA/n_lbl_euvhr.nc -np $procs \
     > ${sp_dir}/n_euvhr_log
fi

# Nitrogen Trioxide (NO3)
#dat2xsc NO3.dat no3.uvxsc
UV_NO3='no3.uvxsc' #   400nm - 793 nm
if [ ! -s ${sp_dir}/no3_uv_l ] || [ ! -s $SW_DATA/no3_lbl.nc ] ; then
  echo 'NO3 (UV)'
  rm -f ${sp_dir}/no3_uv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_NO3 \
    -R 400 794 -i 1.0 -l 41 2.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/no3_uv_l -m ${sp_dir}/no3_uv_lm \
    -L $SW_DATA/no3_lbl.nc -np $procs \
     > ${sp_dir}/no3_uv_log
fi

# Dinitrogen Pentoxide (N2O5)
UV_N2O5='n2o5.uvxsc' # 152 - 397 nm
if [ ! -s ${sp_dir}/n2o5_uv_l ] || [ ! -s $SW_DATA/n2o5_lbl.nc ] ; then
  echo 'N2O5 (UV)'
  rm -f ${sp_dir}/n2o5_uv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_N2O5 \
    -R 152 398 -i 1.0 -l 42 2.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/n2o5_uv_l -m ${sp_dir}/n2o5_uv_lm \
    -L $SW_DATA/n2o5_lbl.nc -np $procs \
     > ${sp_dir}/n2o5_uv_log
fi

#Nitrous Acid (HONO)
rm -f hono.uvxsc
dat2xsc HONO.dat hono.uvxsc
UV_HONO='hono.uvxsc' #   184nm - 396 nm
if [ ! -s ${sp_dir}/hono_uv_l ] || [ ! -s $SW_DATA/hono_lbl.nc ] ; then
  echo 'HONO (UV)'
  rm -f ${sp_dir}/hono_uv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_HONO \
    -R 184 397 -i 1.0 -l 43 1.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/hono_uv_l -m ${sp_dir}/hono_uv_lm \
    -L $SW_DATA/hono_lbl.nc -np $procs \
     > ${sp_dir}/hono_uv_log
fi

#Peroxynitric Acid (HO2NO2)
#rm -f ho2no2.uvxsc
#dat2xsc HO2NO2.dat ho2no2.uvxsc
UV_HO2NO2='ho2no2_cat.uvxsc' #   190nm - 349 nm
ho2no2_pt_file='pt_ho2no2'
if [ ! -s ${sp_dir}/ho2no2_uv_l ] || [ ! -s $SW_DATA/ho2no2_lbl.nc ] ; then
  echo 'HO2NO2 (UV)'
  rm -f ${sp_dir}/ho2no2_uv_l*
  Ccorr_k -F $ho2no2_pt_file -UVX $UV_HO2NO2 \
    -R 190 1376 -i 1.0 -l 44 2.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -q -r $REF_PT_FILE \
    -o ${sp_dir}/ho2no2_uv_l -m ${sp_dir}/ho2no2_uv_lm \
    -L $SW_DATA/ho2no2_lbl.nc -np $procs \
     > ${sp_dir}/ho2no2_uv_log
fi

#Hydrogen Peroxide (H2O2)
calc_h2o2_xsc
dat2xsc -t 200 h2o2_200K.dat h2o2_200K.uvxsc
dat2xsc -t 220 h2o2_220K.dat h2o2_220K.uvxsc
dat2xsc -t 240 h2o2_240K.dat h2o2_240K.uvxsc
dat2xsc -t 260 h2o2_260K.dat h2o2_260K.uvxsc
dat2xsc -t 280 h2o2_280K.dat h2o2_280K.uvxsc
dat2xsc -t 298 h2o2_298K.dat h2o2_298K.uvxsc
dat2xsc -t 320 h2o2_320K.dat h2o2_320K.uvxsc
cat h2o2_???K.uvxsc > h2o2.uvxsc
UV_H2O2='h2o2.uvxsc' #   190nm - 350 nm
h2o2_pt_file='pt_h2o2'
if [ ! -s ${sp_dir}/h2o2_uv_l ] || [ ! -s $SW_DATA/h2o2_lbl.nc ] ; then
  echo 'H2O2 (UV)'
  rm -f ${sp_dir}/h2o2_uv_l*
  Ccorr_k -F $h2o2_pt_file -UVX $UV_H2O2 \
    -R 190 350 -i 1.0 -l 45 2.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -q -r $REF_PT_FILE \
    -o ${sp_dir}/h2o2_uv_l -m ${sp_dir}/h2o2_uv_lm \
    -L $SW_DATA/h2o2_lbl.nc -np $procs \
     > ${sp_dir}/h2o2_uv_log
fi

#Ethane (C2H6)
UV_C2H6="${hj}/c2h6.uvxsc"  #   6nm - 159 nm
if [ ! -s ${sp_dir}/c2h6_xuv_l ] || [ ! -s $SW_DATA/c2h6_lbl_xuv.nc ] ; then
  echo 'C2H6 (XUV)'
  rm -f ${sp_dir}/c2h6_xuv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_C2H6 \
    -R 6 10 -i 1000.0 -l 46 1.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/c2h6_xuv_l -m ${sp_dir}/c2h6_xuv_lm \
    -L $SW_DATA/c2h6_lbl_xuv.nc -np $procs \
     > ${sp_dir}/c2h6_xuv_log
fi
if [ ! -s ${sp_dir}/c2h6_euv_l ] || [ ! -s $SW_DATA/c2h6_lbl_euv.nc ] ; then
  echo 'C2H6 (EUV)'
  rm -f ${sp_dir}/c2h6_euv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_C2H6 \
    -R 11 100 -i 10.0 -l 46 1.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/c2h6_euv_l -m ${sp_dir}/c2h6_euv_lm \
    -L $SW_DATA/c2h6_lbl_euv.nc -np $procs \
     > ${sp_dir}/c2h6_euv_log
fi
if [ ! -s ${sp_dir}/c2h6_uv_l ] || [ ! -s $SW_DATA/c2h6_lbl_uv.nc ] ; then
  echo 'C2H6 (UV)'
  rm -f ${sp_dir}/c2h6_uv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_C2H6 \
    -R 101 160 -i 1.0 -l 46 1.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/c2h6_uv_l -m ${sp_dir}/c2h6_uv_lm \
    -L $SW_DATA/c2h6_lbl_uv.nc -np $procs \
     > ${sp_dir}/c2h6_uv_log
fi

#Methanal (H2CO)
UV_H2CO='h2co.uvxsc' #   226nm - 370 nm
h2co_pt_file='pt_h2co'
if [ ! -s ${sp_dir}/h2co_xuv_l ] || [ ! -s $SW_DATA/h2co_lbl_xuv.nc ] ; then
  echo 'H2CO (XUV)'
  rm -f ${sp_dir}/h2co_xuv_l*
  Ccorr_k -F $h2co_pt_file -UVX $UV_H2CO \
    -R 7 10 -i 1000.0 -l 48 2.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -q -r $REF_PT_FILE \
    -o ${sp_dir}/h2co_xuv_l -m ${sp_dir}/h2co_xuv_lm \
    -L $SW_DATA/h2co_lbl_xuv.nc -np $procs \
     > ${sp_dir}/h2co_xuv_log
fi
if [ ! -s ${sp_dir}/h2co_euv_l ] || [ ! -s $SW_DATA/h2co_lbl_euv.nc ] ; then
  echo 'H2CO (EUV)'
  rm -f ${sp_dir}/h2co_euv_l*
  Ccorr_k -F $h2co_pt_file -UVX $UV_H2CO \
    -R 11 100 -i 10.0 -l 48 2.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -q -r $REF_PT_FILE \
    -o ${sp_dir}/h2co_euv_l -m ${sp_dir}/h2co_euv_lm \
    -L $SW_DATA/h2co_lbl_euv.nc -np $procs \
     > ${sp_dir}/h2co_euv_log
fi
if [ ! -s ${sp_dir}/h2co_uv_l ] || [ ! -s $SW_DATA/h2co_lbl_uv.nc ] ; then
  echo 'H2CO (UV)'
  rm -f ${sp_dir}/h2co_uv_l*
  Ccorr_k -F $h2co_pt_file -UVX $UV_H2CO \
    -R 101 376 -i 1.0 -l 48 2.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -q -r $REF_PT_FILE \
    -o ${sp_dir}/h2co_uv_l -m ${sp_dir}/h2co_uv_lm \
    -L $SW_DATA/h2co_lbl_uv.nc -np $procs \
     > ${sp_dir}/h2co_uv_log
fi

#Acetaldehyde (CH3CHO)
rm -f ch3cho.uvxsc
dat2xsc CH3CHO.dat ch3cho.uvxsc
UV_CH3CHO='ch3cho.uvxsc' #   202nm - 360 nm
if [ ! -s ${sp_dir}/ch3cho_uv_l ] || [ ! -s $SW_DATA/ch3cho_lbl.nc ] ; then
  echo 'CH3CHO (UV)'
  rm -f ${sp_dir}/ch3cho_uv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_CH3CHO \
    -R 202 361 -i 1.0 -l 56 1.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/ch3cho_uv_l -m ${sp_dir}/ch3cho_uv_lm \
    -L $SW_DATA/ch3cho_lbl.nc -np $procs \
     > ${sp_dir}/ch3cho_uv_log
fi

#Methylhydroperoxide (CH3OOH)
rm -f ch3ooh.uvxsc
dat2xsc CH3OOH.dat ch3ooh.uvxsc
UV_CH3OOH='ch3ooh.uvxsc' #   210nm - 405 nm
if [ ! -s ${sp_dir}/ch3ooh_uv_l ] || [ ! -s $SW_DATA/ch3ooh_lbl.nc ] ; then
  echo 'CH3OOH (UV)'
  rm -f ${sp_dir}/ch3ooh_uv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_CH3OOH \
    -R 210 406 -i 1.0 -l 57 1.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/ch3ooh_uv_l -m ${sp_dir}/ch3ooh_uv_lm \
    -L $SW_DATA/ch3ooh_lbl.nc -np $procs \
     > ${sp_dir}/ch3ooh_uv_log
fi

#Acetone (CH3COCH3)
UV_CH3COCH3='ch3coch3.uvxsc' #   215nm - 349 nm
ch3coch3_pt_file='pt_ch3coch3'
if [ ! -s ${sp_dir}/ch3coch3_uv_l ] || [ ! -s $SW_DATA/ch3coch3_lbl.nc ] ; then
  echo 'CH3COCH3 (UV)'
  rm -f ${sp_dir}/ch3coch3_uv_l*
  Ccorr_k -F $ch3coch3_pt_file -UVX $UV_CH3COCH3 \
    -R 215 350 -i 1.0 -l 58 1.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -q -r $REF_PT_FILE \
    -o ${sp_dir}/ch3coch3_uv_l -m ${sp_dir}/ch3coch3_uv_lm \
    -L $SW_DATA/ch3coch3_lbl.nc -np $procs \
     > ${sp_dir}/ch3coch3_uv_log
fi

#Methylglyoxal (CH3COCHO)
rm -f ch3cocho.uvxsc
dat2xsc CH3COCHO.dat ch3cocho.uvxsc
UV_CH3COCHO='ch3cocho.uvxsc' # 200 - 493 nm
if [ ! -s ${sp_dir}/ch3cocho_uv_l ] || [ ! -s $SW_DATA/ch3cocho_lbl.nc ] ; then
  echo 'CH3COCHO (UV)'
  rm -f ${sp_dir}/ch3cocho_uv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_CH3COCHO \
    -R 200 494 -i 1.0 -l 59 2.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/ch3cocho_uv_l -m ${sp_dir}/ch3cocho_uv_lm \
    -L $SW_DATA/ch3cocho_lbl.nc -np $procs \
     > ${sp_dir}/ch3cocho_uv_log
fi

#Glyoxal (CHOCHO)
rm -f chocho.uvxsc
dat2xsc CHOCHO.dat chocho.uvxsc
UV_CHOCHO='chocho.uvxsc' #   250nm - 526 nm
if [ ! -s ${sp_dir}/chocho_uv_l ] || [ ! -s $SW_DATA/chocho_lbl.nc ] ; then
  echo 'CHOCHO (UV)'
  rm -f ${sp_dir}/chocho_uv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_CHOCHO \
    -R 250 527 -i 1.0 -l 60 1.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/chocho_uv_l -m ${sp_dir}/chocho_uv_lm \
    -L $SW_DATA/chocho_lbl.nc -np $procs \
     > ${sp_dir}/chocho_uv_log
fi

#Glycolaldehyde (HOCH2CHO)
rm -f hoch2cho.uvxsc
dat2xsc HOCH2CHO.dat hoch2cho.uvxsc
UV_HOCH2CHO='hoch2cho.uvxsc' #   208nm - 332 nm
if [ ! -s ${sp_dir}/hoch2cho_uv_l ] || [ ! -s $SW_DATA/hoch2cho_lbl.nc ] ; then
  echo 'HOCH2CHO (UV)'
  rm -f ${sp_dir}/hoch2cho_uv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_HOCH2CHO \
    -R 208 333 -i 1.0 -l 62 2.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/hoch2cho_uv_l -m ${sp_dir}/hoch2cho_uv_lm \
    -L $SW_DATA/hoch2cho_lbl.nc -np $procs \
     > ${sp_dir}/hoch2cho_uv_log
fi

#Methacrolein (MACR)
#rm -f macr.uvxsc
#dat2xsc MACR.dat macr.uvxsc
#UV_MACR='macr.uvxsc' #   250nm - 395 nm
#if [ ! -s ${sp_dir}/macr_uv_l ] || [ ! -s $SW_DATA/macr_lbl.nc ] ; then
#  echo 'MACR (UV)'
#  rm -f ${sp_dir}/macr_uv_l*
#  Ccorr_k -F $PT_SINGLE -UVX $UV_MACR \
#    -R 250 396 -i 1.0 -l 65 2.0e-3 -t 1.0e-3  \
#    -s $skelfile +S $SOLSPEC \
#    -o ${sp_dir}/macr_uv_l -m ${sp_dir}/macr_uv_lm \
#    -L $SW_DATA/macr_lbl.nc -np $procs \
#     > ${sp_dir}/macr_uv_log
#fi

#Polyacrylonitrile (PAN)
UV_PAN='pan.uvxsc' #   196nm - 350 nm
pan_pt_file='pt_pan'
if [ ! -s ${sp_dir}/pan_uv_l ] || [ ! -s $SW_DATA/pan_lbl.nc ] ; then
  echo 'PAN (UV)'
  rm -f ${sp_dir}/pan_uv_l*
  Ccorr_k -F $pan_pt_file -UVX $UV_PAN \
    -R 196 351 -i 1.0 -l 66 1.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC -q -r $REF_PT_FILE \
    -o ${sp_dir}/pan_uv_l -m ${sp_dir}/pan_uv_lm \
    -L $SW_DATA/pan_lbl.nc -np $procs \
     > ${sp_dir}/pan_uv_log
fi

#Methylnitrate (CH3ONO2)
rm -f ch3ono2.uvxsc
dat2xsc CH3ONO2.dat ch3ono2.uvxsc
UV_CH3ONO2='ch3ono2.uvxsc' #   192nm - 344 nm
if [ ! -s ${sp_dir}/ch3ono2_uv_l ] || [ ! -s $SW_DATA/ch3ono2_lbl.nc ] ; then
  echo 'CH3ONO2 (UV)'
  rm -f ${sp_dir}/ch3ono2_uv_l*
  Ccorr_k -F $PT_SINGLE -UVX $UV_CH3ONO2 \
    -R 192 345 -i 1.0 -l 67 2.0e-3 -t 1.0e-3  \
    -s $skelfile +S $SOLSPEC \
    -o ${sp_dir}/ch3ono2_uv_l -m ${sp_dir}/ch3ono2_uv_lm \
    -L $SW_DATA/ch3ono2_lbl.nc -np $procs \
     > ${sp_dir}/ch3ono2_uv_log
fi

wait

# Create the spectral file from the data calculated above
# -------------------------------------------------------
echo 'Constructing spectral file'
mv ${specfile} ${specfile}_old 2> /dev/null
mv ${specfile}_k ${specfile}_old_k 2> /dev/null
prep_spec << EOF > ${specfile}_log1 2>&1
$skelfile
n
$specfile
2
n
${SOLSPEC}
n
3
a
5
${sp_dir}/o2_xuvhr_l
5
y
${sp_dir}/o2_euvhr_l
5
y
${sp_dir}/o2_uvhr_l
5
y
${sp_dir}/o3_uvhr_l
5
y
${sp_dir}/ch4_xuv_l
5
y
${sp_dir}/ch4_euv_l
5
y
${sp_dir}/ch4_uv_l
5
y
${sp_dir}/co2_xuv_l
5
y
${sp_dir}/co2_euv_l
5
y
${sp_dir}/co2_uv_l
5
y
${sp_dir}/co_xuv_l
5
y
${sp_dir}/co_euv_l
5
y
${sp_dir}/co_uv_l
5
y
${sp_dir}/h2_xuv_l
5
y
${sp_dir}/h2_euv_l
5
y
${sp_dir}/h2_uv_l
5
y
${sp_dir}/h2o_xuv_l
5
y
${sp_dir}/h2o_euv_l
5
y
${sp_dir}/h2o_uv_l
5
y
${sp_dir}/n2_xuvhr_l
5
y
${sp_dir}/n2_euvhr_l
5
y
${sp_dir}/n2o_xuv_l
5
y
${sp_dir}/n2o_euv_l
5
y
${sp_dir}/n2o_fuv_l
5
y
${sp_dir}/n2o_uv_l
5
y
${sp_dir}/no2_xuv_l
5
y
${sp_dir}/no2_euv_l
5
y
${sp_dir}/no2_uv_l
5
y
${sp_dir}/o_xuvhr_l
5
y
${sp_dir}/o_euvhr_l
5
y
${sp_dir}/n_xuvhr_l
5
y
${sp_dir}/n_euvhr_l
5
y
${sp_dir}/h2o2_uv_l
5
y
${sp_dir}/no3_uv_l
5
y
${sp_dir}/n2o5_uv_l
5
y
${sp_dir}/ho2no2_uv_l
5
y
${sp_dir}/hno3_uv_l
5
y
${sp_dir}/ch3ooh_uv_l
5
y
${sp_dir}/hono_uv_l
5
y
${sp_dir}/ch3cho_uv_l
5
y
${sp_dir}/h2co_xuv_l
5
y
${sp_dir}/h2co_euv_l
5
y
${sp_dir}/h2co_uv_l
5
y
${sp_dir}/chocho_uv_l
5
y
${sp_dir}/ocs_uv_l
5
y
${sp_dir}/ch3ono2_uv_l
5
y
${sp_dir}/hoch2cho_uv_l
5
y
${sp_dir}/pan_uv_l
5
y
${sp_dir}/ch3cocho_uv_l
5
y
${sp_dir}/ch3coch3_uv_l
5
y
${sp_dir}/c2h2_xuv_l
5
y
${sp_dir}/c2h2_euv_l
5
y
${sp_dir}/c2h2_uv_l
5
y
${sp_dir}/hcn_euv_l
5
y
${sp_dir}/hcn_uv_l
5
y
${sp_dir}/c2h6_xuv_l
5
y
${sp_dir}/c2h6_euv_l
5
y
${sp_dir}/c2h6_uv_l
5
y
${sp_dir}/nh3_xuv_l
5
y
${sp_dir}/nh3_euv_l
5
y
${sp_dir}/nh3_uv_l
-1
EOF

# Rearrange so the major gas is listed first for each band
echo 'Determining major absorbers'
# Column ammounts integrated down to     stratopause  |  mesopause
# Column amount for Water Vapour         0.156458E-04    0.630611E-08
# Column amount for Carbon Dioxide       0.251123E-02    0.708379E-05
# Column amount for Ozone                0.784418E-05    0.128860E-07
# Column amount for Dinitrogen Oxide     0.138654E-07    0.103199E-10
# Column amount for Carbon monoxide      0.112071E-05    0.208955E-06
# Column amount for Methane              0.399384E-06    0.123864E-08
# Column amount for Oxygen               0.107215E+01    0.332647E-02
# Column amount for Nitrogen monoxide            0.356393E-05
# Column amount for Nitrogen dioxide     0.205777E-08    0.482538E-11
# Column amount for Ammonia                          0.0
# Column amount for Nitric acid                      0.0
# Column amount for Nitrogen             0.351191E+01    0.130265E-01
# Column amount for Hydrogen                         0.0
# Column amount for Carbonyl sulphide                0.0
# Column amount for Acetylene                        0.0
# Column amount for Hydrogen cyanide                 0.0
# Column amount for Atomic Oxygen        0.262064E-03    0.228072E-03
# Column amount for Atomic Nitrogen      0.299410E-09    0.260047E-09
# Column amount for Nitrate radical                  0.0
# Column amount for Dinitrogen pentoxide             0.0
# Column amount for Nitrous acid                     0.0
# Column amount for Peroxynitric acid                0.0
# Column amount for Hydrogen peroxide                0.0
# Column amount for Ethane                           0.0
# Column amount for Formaldehyde                     0.0
# Column amount for Acetaldehyde                     0.0
# Column amount for Methylhydroperoxide              0.0
# Column amount for Acetone                          0.0
# Column amount for Methylglyoxal                    0.0
# Column amount for Glyoxal                          0.0
# Column amount for Glycolaldehyde                   0.0
# Column amount for Peroxyacetyl nitrate             0.0
# Column amount for Methylnitrate                    0.0
tidy_90 <<EOF > ${specfile}_tidy_log
${specfile}
o
6
0.630611E-08
0.708379E-05
0.128860E-07
0.103199E-10
0.208955E-06
0.123864E-08
0.332647E-02
0.356393E-05
0.482538E-11
0.0
0.0
0.130265E-01
0.0
0.0
0.0
0.0
0.228072E-03
0.260047E-09
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
-1
EOF

# Define sub-bands and photolysis reactions
echo 'Adding photolysis reactions'
prep_spec << EOF > ${specfile}_log2 2>&1
${specfile}
a
17
-1
${SOLSPEC}
a
0
0
0
20
7
1
n
O2_1.qy
O2_1.pe
20
y
7
2
n
O2_2.qy
O2_2.pe
20
y
7
6
n
O2_6.qy
O2_6.pe
20
y
7
7
n
O2_7.qy
O2_7.pe
20
y
13
1
n
N2_1.qy
N2_1.pe
20
y
13
2
n
N2_2.qy
N2_2.pe
20
y
13
3
n
N2_3.qy
N2_3.pe
20
y
39
1
n
O_1.qy
O_1.pe
20
y
39
2
n
O_2.qy
O_2.pe
20
y
39
3
n
O_3.qy
O_3.pe
20
y
39
4
n
O_4.qy
O_4.pe
20
y
39
5
n
O_5.qy
O_5.pe
20
y
40
1
n
N_1.qy
N_1.pe
20
y
1
2
n
${hj}/H2O_2.qy

20
y
1
3
n
${hj}/H2O_3.qy

20
y
1
5
n
${hj}/H2O_5.qy

20
y
3
1
y
O3_Matsumi2002_1.qy

20
y
3
4
y
O3_Matsumi2002_4.qy

20
y
10
1
y
NO2_jpl_1.qy

20
y
45
1
y
H2O2_1.qy

20
y
42
1
y
N2O5_1.qy

20
y
41
1
y
NO3_1.qy

20
y
44
2
y
HO2NO2_jpl_2.qy

20
y
41
2
y
NO3_2.qy


20
y
12
1
y
HNO3_1.qy

20
y
57
1
y
CH3OOH_1.qy

20
y
43
1
y
HONO_1.qy

20
y
56
1
y
CH3CHO_1.qy

20
y
48
1
y
H2CO_1.qy

20
y
48
2
y
H2CO_2.qy

20
y
60
1
y
CHOCHO_1.qy

20
y
60
2
y
CHOCHO_2.qy

20
y
25
1
y
OCS_1.qy

20
y
67
1
y
CH3ONO2_1.qy

20
y
62
1
y
HOCH2CHO_1.qy

20
y
66
1
y
PAN_1.qy

20
y
66
2
y
PAN_2.qy

20
y
4
1
y
N2O_1.qy

20
y
59
1
y
CH3COCHO_1.qy

20
y
58
1
y
CH3COCH3_1.qy

20
y
2
1
y
${hj}/CO2_1.qy

20
y
2
2
y
${hj}/CO2_2.qy

20
y
34
1
y
${hj}/C2H2_1.qy

20
y
6
1
y
${hj}/CH4_1.qy

20
y
6
2
y
${hj}/CH4_2.qy

20
y
6
3
y
${hj}/CH4_3.qy

20
y
6
4
y
${hj}/CH4_4.qy

20
y
35
1
y
${hj}/HCN_1.qy

20
y
46
1
y
${hj}/C2H6_1.qy

20
y
46
2
y
${hj}/C2H6_2.qy

20
y
46
3
y
${hj}/C2H6_3.qy

20
y
46
4
y
${hj}/C2H6_4.qy

20
y
46
5
y
${hj}/C2H6_5.qy

20
y
11
1
y
${hj}/NH3_1.qy

-1
EOF

echo -n 'Finished mk_sp_2000_earth: '; date
exit 0
