#!/bin/bash

if [ $RAD_BIN ] ; then
  echo "Using code compiled in "$RAD_BIN
else
  echo "Path to code not set."
  exit 1
fi

skelfile=$1
if [ ! -s ${skelfile} ] ; then

# Create skeleton spectral file:
# 2000 bands
prep_spec << EOF > ${skelfile}_log
${skelfile}
2000
33
1
2
3
4
5
6
7
8
10
11
12
13
23
25
34
35
39
40
41
42
43
44
45
46
48
56
57
58
59
60
62
66
67
0
0
r
m 0.1E-9 1.0E-9 0.9E-9
m 1.0E-9 1.0E-6 1.0E-9
c 10000.0 10.0 -10.0
c 10.0 1.0 -9.0
0*2000
0*2000
n
-1
EOF

fi
exit 0
