#! /bin/bash
#
# SCRIPT TO GENERATE MIE SCATTERING DATA FOR ONE EFFECTIVE RADIUS ACROSS
# ONE OF ROCKEL'S DISTRIBUTIONS.
#

for NE in 0.01 0.1 0.175 0.25
do 
echo "Effective Radius and Variance: ${1} $NE"
DIST=`./convert $1 $NE`
#echo $DIST
Cscatter -w $RAD_DATA/cloud/wl_water_ext \
         -r $RAD_DATA/cloud/refract_water_ext \
         -c -M -o ss_drop_ext${1}_${NE} \
         -t 2 -n 1.e8 -m 1.0 $DIST
done
