#!/bin/bash

# Initialise error status (to test for output differences)
ierr=0
rm -f convert scatter_drop_ext 2>/dev/null

cc -o convert convert.c
for RE in 1.0 1.5 2.0 3.0 4.5 6.0 7.5 9.0 10.5 12.0 13.5 15.0 16.5 18.0 \
          20.0 22.0 24.0 26.0 28.0 30.0 33.0 36.0 39.0 42.0 46.0 50.0 55.0
do
  if [ ! -s ss_drop_ext${RE}_0.1 ] ; then
    ./run_scatter_ext ${RE} &
  fi
done
wait

for RE in 1.0 1.5 2.0 3.0 4.5 6.0 7.5 9.0 10.5 12.0 13.5 15.0 16.5 18.0 \
          20.0 22.0 24.0 26.0 28.0 30.0 33.0 36.0 39.0 42.0 46.0 50.0 55.0
do
   cat ss_drop_ext${RE}* >> scatter_drop_ext
done

diff -q scatter_drop_ext ${RAD_DATA}/cloud/scatter_drop_ext || \
 ierr=1

if [ $ierr -gt 0 ] ; then
  exit 1
else
  rm -f ss_drop_ext* convert scatter_drop_ext 2>/dev/null
  echo OK
  exit 0
fi
