#! /bin/ksh
#set -xv
#
# Script to run the correlated-k program
#
touch $LOCK_FILE
#
# Store the original positional parameters since they will be
# overwritten by set_param_mod.
#
ARG=$*
#
# Obtain Configured values of parameters
#
. $RAD_SCRIPT/set_param_mod rad_pcf.f90
. $RAD_SCRIPT/set_param_mod weighting_pcf.f90
# WARNING: C-K Fit types and gases are hard-wired at the moment
#
# Restore the original positional parameters.
#
set -- $ARG
#
#
# Process options
#
# Initial versions
#
CTN_ADJUST=n
FRN_INCLUDE=n
#
while [ $# -gt 0 ]
do case $1 in
      -C) CTN_NUM_PATH=$2 ; CTN_MIN_PATH=$3 ; CTN_MAX_PATH=$4 ; shift 4 ;;
      -D) DATABASE=$2 ; shift 2 ;;
      -X) XDATABASE=$2 ; shift 2 ;;
      -L) LBL_FILE=$2 ; shift 2 ;;
      -F) FILE_PT=$2 ; shift 2 ;;
      -I) INST_FILE=$2 ; shift 2 ;;
      -T) DRYRUN=y ; shift ;;
      -P) CTN_NUM_PP=$2 ; shift 2 ;;
      -R) BAND_1=$2 ; BAND_2=$3 ; shift 3 ;;
      -c) CUTOFF=$2 ; shift 2 ;;
      -e) SELF_CF_296=$2 ; SELF_CF_260=$3 ; shift 3 ;;
      -f) FRN_CF=y ; FRN_CF_FILE=$2 ; shift 2 ;;
      -i) LINE_INC=$2 ; shift 2 ;;
      -k) CTN_ADJUST=y ; shift ;;
      -l) LINE_DATA=y ; GAS=$2 ; LINE_MAX_PATH=$3 ; shift 3 ;;
      -s) SPECTRUM=$2 ; shift 2 ;;
      -x) FRN_INCLUDE=y ; LINE_FRN_CF=y ; FRN_CF_FILE=$2 ; shift 2 ;;
      +S) WEIGHT=$IP_WEIGHT_SOLAR ; SOLAR_FILE=$2 ; shift 2 ;;
      +p) WEIGHT=$IP_WEIGHT_PLANCK ; shift ;;
      +d) WEIGHT=$IP_WEIGHT_DPLANCK ; shift ;;
      -u) WEIGHT=$IP_WEIGHT_UNIFORM ; shift ;;
      -n) FIT_TYPE=2 ; NUM_K=$2 ; shift 2 ;;
      -m) MON_FILE=$2 ; shift 2 ;;
      -o) OUT_FILE=$2 ; shift 2 ;;
      -t) FIT_TYPE=1 ; TOL=$2 ; shift 2 ;;
      -b) FIT_TYPE=3 ; TOL=$2 ; shift 2 ;;
      -r) REF_PT_FILE=$2 ; shift 2 ;;
      -p) SCALE_FNC=$IP_SCALE_POWER_LAW ; shift ;;
      -q) SCALE_FNC=$IP_SCALE_POWER_QUAD ; shift ;;
      -d) SCALE_FNC=$IP_SCALE_DOPPLER_QUAD ; shift ;;
      -p2) SCALE_FNC=$IP_SCALE_DBL_POW_LAW ; shift ;;
      -q2) SCALE_FNC=$IP_SCALE_DBL_POW_QUAD ; shift ;;
      -d2) SCALE_FNC=$IP_SCALE_DBL_DOP_QUAD ; shift ;;
      -lk) SCALE_FNC=$IP_SCALE_LOOKUP ; shift ;;
      -*) echo "Error: invalid option" ; exit 1 ;;
      +*) echo "Error: invalid option" ; exit 1 ;;
   esac
done
#
if [ "$SELF_CF_296" ] || [ "$FRN_CF" ]
  then GAS=1
fi
#
echo $LBL_FILE > /tmp/ck.$$
#
# Line list
#
if [ "$DATABASE" ]
  then echo l >> /tmp/ck.$$
  echo $DATABASE >> /tmp/ck.$$
  echo $RAD_DATA/gases/parsum.dat >> /tmp/ck.$$
else
  if [ "$XDATABASE" ]
    then echo x >> /tmp/ck.$$
    echo $XDATABASE >> /tmp/ck.$$
  else
    echo n >> /tmp/ck.$$
  fi
fi
echo $SPECTRUM >> /tmp/ck.$$
#
# Type of data to be generated.
#
if [ "$INST_FILE" ]
  then echo y >> /tmp/ck.$$
  echo $INST_FILE >> /tmp/ck.$$
else
  echo n >> /tmp/ck.$$
fi
if [ "$LINE_DATA" ]
  then echo y >> /tmp/ck.$$
else
  echo n >> /tmp/ck.$$
fi
if [ "$FRN_CF" ]
  then echo y >> /tmp/ck.$$
  echo $FRN_CF_FILE >> /tmp/ck.$$
else
  echo n >> /tmp/ck.$$
fi
if [ "$SELF_CF_296" ]
  then echo y >> /tmp/ck.$$
  echo $SELF_CF_296 >> /tmp/ck.$$
  echo $SELF_CF_260 >> /tmp/ck.$$
else
  echo n >> /tmp/ck.$$
fi
#
# Actual gas
#
if [ "$LINE_DATA" ]
  then echo $GAS >> /tmp/ck.$$
fi
#
# Selection of bands
#
echo $BAND_1 $BAND_2 >> /tmp/ck.$$
#
# Selection of pressures and temperatures.
#
echo f >> /tmp/ck.$$
echo $FILE_PT >> /tmp/ck.$$
#
# Selection of scaling functions.
#
if [ "$SCALE_FNC" ]
  then echo "y" >> /tmp/ck.$$
       echo $SCALE_FNC >> /tmp/ck.$$
       if [ $SCALE_FNC -ne $IP_SCALE_LOOKUP ]
         then echo "f" >> /tmp/ck.$$
              echo $REF_PT_FILE >> /tmp/ck.$$
       fi
else
  echo "n" >> /tmp/ck.$$
fi
#
# Details of line integration.
#
if [ "$DATABASE" ] && ([ "$LINE_DATA" ] || [ "$FRN_CF" ] || [ "$SELF_CF_296" ])
  then if [ $GAS -eq 1 ]
          then echo $CTN_ADJUST >> /tmp/ck.$$
               echo $FRN_INCLUDE >> /tmp/ck.$$
               if [ "$LINE_FRN_CF" ]
                 then echo $FRN_CF_FILE >> /tmp/ck.$$
               fi
       fi
  echo $CUTOFF >> /tmp/ck.$$
  echo $LINE_INC >> /tmp/ck.$$
else
  if [ "$XDATABASE" ]
    then echo $LINE_INC >> /tmp/ck.$$
  fi
fi
if [ "$FRN_CF" ] || [ "$SELF_CF_296" ]
  then echo $CTN_MIN_PATH >> /tmp/ck.$$
       echo $CTN_MAX_PATH >> /tmp/ck.$$
       echo $CTN_NUM_PATH >> /tmp/ck.$$
       echo $CTN_NUM_PP >> /tmp/ck.$$
fi
if [ "$LINE_DATA" ]
  then echo $FIT_TYPE >> /tmp/ck.$$
       case $FIT_TYPE in
         1) echo $TOL >> /tmp/ck.$$ ;;
         2) echo $NUM_K >> /tmp/ck.$$ ;;
         3) echo $TOL >> /tmp/ck.$$ ;;
       esac
       echo $LINE_MAX_PATH >> /tmp/ck.$$
fi
echo $WEIGHT >> /tmp/ck.$$
if [ $WEIGHT -eq $IP_WEIGHT_SOLAR ]
then echo $SOLAR_FILE >> /tmp/ck.$$
fi
echo $OUT_FILE >> /tmp/ck.$$
echo $MON_FILE >> /tmp/ck.$$
if [ "$DRYRUN" ]
  then echo /tmp/ck.$$
else
  ( corr_k < /tmp/ck.$$ ) 
#> /dev/null
fi
rm -f $LOCK_FILE
