#!/bin/bash

# Initialise error status (to test for output differences)
ierr=0

# Download CMIP5 solar variability data
wget -nc http://solarisheppa.geomar.de/solarisheppa/sites/default/files/data/CMIP5/spectra_1610_2000a_21Jan09.txt.gz
wget -nc http://solarisheppa.geomar.de/solarisheppa/sites/default/files/data/CMIP5/spectra_1882_2000m_17Dec08.txt.gz
wget -nc http://solarisheppa.geomar.de/solarisheppa/sites/default/files/data/CMIP5/spectra_2000_2008m_6May09.txt.gz
cp spectra_1610_2000a_21Jan09.txt.gz spectra_1610_2000a_21Jan09.txt.gz2
cp spectra_1882_2000m_17Dec08.txt.gz spectra_1882_2000m_17Dec08.txt.gz2
cp spectra_2000_2008m_6May09.txt.gz spectra_2000_2008m_6May09.txt.gz2
gunzip -f *.gz
mv spectra_1610_2000a_21Jan09.txt.gz2 spectra_1610_2000a_21Jan09.txt.gz
mv spectra_1882_2000m_17Dec08.txt.gz2 spectra_1882_2000m_17Dec08.txt.gz
mv spectra_2000_2008m_6May09.txt.gz2 spectra_2000_2008m_6May09.txt.gz

# Remove files created by previous runs
rm -f sp_sw_ga7*

# Copy GA7 shortwave spectral file here and remove block 17
# to illustrate creation of block from scratch
cp ../../data/spectra/ga7/sp_sw_ga7 .
cp ../../data/spectra/ga7/sp_sw_ga7_k .
sed -i '/BLOCK: TYPE =   17/,/END/d' sp_sw_ga7

# Add solar variability data to spectral file
prep_spec << EOF
sp_sw_ga7
a
17
1
e
2
l
320.e-9 400.e-9
400.e-9 505.e-9
0
../../data/solar/lean_12
a
8
272
spectra_1610_2000a_21Jan09.txt
1416
spectra_1882_2000m_17Dec08.txt
108
spectra_2000_2008m_6May09.txt
0
144
-1
EOF

# Check that block 17 was created successfully
diff -q sp_sw_ga7 ../../data/spectra/ga7/sp_sw_ga7 || ierr=1

if [ $ierr -gt 0 ] ; then
  exit 1
else
  rm -f *.txt 2>/dev/null
  echo OK
  exit 0
fi
